/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202502GetLiveRoomUserPortraitsResponseDataAllAdsAgeIndicators {
    /**
    * The type of age indicator. USER_PORTRAIT_AGE_LESS_THAN_15: Users whose age is less than 15. USER_PORTRAIT_AGE_MORE_THAN_34: Users whose age is more than 34. USER_PORTRAIT_AGE_MORE_THAN_55: Users whose age is more than 55. USER_PORTRAIT_AGE_13_TO_17: Users whose age is between 13 and 17. USER_PORTRAIT_AGE_15_TO_17: Users whose age is between 15 and 17. USER_PORTRAIT_AGE_18_TO_24: Users whose age is between 18 and 24. USER_PORTRAIT_AGE_25_TO_34: Users whose age is between 25 and 34. USER_PORTRAIT_AGE_35_TO_44: Users whose age is between 35 and 44. USER_PORTRAIT_AGE_45_TO_54: Users whose age is between 45 and 54.
    */
    'type'?: string;
    /**
    * The value for the corresponding age indicator.
    */
    'value'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202502GetLiveRoomUserPortraitsResponseDataAllAdsAgeIndicators.attributeTypeMap;
    }
}

