/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202502GetLiveRoomGMVTrendResponseDataGmvTrendPerformancesDataPointsGmv } from './GetLiveRoomGMVTrendResponseDataGmvTrendPerformancesDataPointsGmv';

export class Analytics202502GetLiveRoomGMVTrendResponseDataGmvTrendPerformancesDataPoints {
    'gmv'?: Analytics202502GetLiveRoomGMVTrendResponseDataGmvTrendPerformancesDataPointsGmv;
    /**
    * If stats_type is TREND_CREATED_ORDER, it will return the  order count in current timestamp
    */
    'orderCount'?: number;
    /**
    * timestamp
    */
    'timestamp'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "gmv",
            "baseName": "gmv",
            "type": "Analytics202502GetLiveRoomGMVTrendResponseDataGmvTrendPerformancesDataPointsGmv"
        },
        {
            "name": "orderCount",
            "baseName": "order_count",
            "type": "number"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202502GetLiveRoomGMVTrendResponseDataGmvTrendPerformancesDataPoints.attributeTypeMap;
    }
}

