/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202502GetLiveRoomTrafficPerformanceResponseDataTrafficPerformances } from './GetLiveRoomTrafficPerformanceResponseDataTrafficPerformances';

export class Analytics202502GetLiveRoomTrafficPerformanceResponseData {
    /**
    * The traffic performances within the livestream room
    */
    'trafficPerformances'?: Array<Analytics202502GetLiveRoomTrafficPerformanceResponseDataTrafficPerformances>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "trafficPerformances",
            "baseName": "traffic_performances",
            "type": "Array<Analytics202502GetLiveRoomTrafficPerformanceResponseDataTrafficPerformances>"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202502GetLiveRoomTrafficPerformanceResponseData.attributeTypeMap;
    }
}

