/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202502GetLiveRoomInteractiveTrendsResponseDataInteractiveTrendPerformancesDataPoints } from './GetLiveRoomInteractiveTrendsResponseDataInteractiveTrendPerformancesDataPoints';

export class Analytics202502GetLiveRoomInteractiveTrendsResponseDataInteractiveTrendPerformances {
    /**
    * The data point of interactive trend
    */
    'dataPoints'?: Array<Analytics202502GetLiveRoomInteractiveTrendsResponseDataInteractiveTrendPerformancesDataPoints>;
    /**
    * The stats_type describes the type of interactive trend value. Possible values: WATCH_PV (watch count of the live streaming room), COMMENT_PV (comment count of the live streaming room), SHARE_PV (share count of the live streaming room).
    */
    'statsType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dataPoints",
            "baseName": "data_points",
            "type": "Array<Analytics202502GetLiveRoomInteractiveTrendsResponseDataInteractiveTrendPerformancesDataPoints>"
        },
        {
            "name": "statsType",
            "baseName": "stats_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202502GetLiveRoomInteractiveTrendsResponseDataInteractiveTrendPerformances.attributeTypeMap;
    }
}

