/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202502GetLiveRoomGMVTrendResponseDataGmvTrendPerformancesDataPoints } from './GetLiveRoomGMVTrendResponseDataGmvTrendPerformancesDataPoints';

export class Analytics202502GetLiveRoomGMVTrendResponseDataGmvTrendPerformances {
    /**
    * The data point of GMV trend 
    */
    'dataPoints'?: Array<Analytics202502GetLiveRoomGMVTrendResponseDataGmvTrendPerformancesDataPoints>;
    /**
    * The stats_type describes the type of trend value. Possible values: TREND_GMV (GMV of the live streaming room), TREND_CREATED_ORDER (created orders in the live streaming room).
    */
    'statsType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dataPoints",
            "baseName": "data_points",
            "type": "Array<Analytics202502GetLiveRoomGMVTrendResponseDataGmvTrendPerformancesDataPoints>"
        },
        {
            "name": "statsType",
            "baseName": "stats_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202502GetLiveRoomGMVTrendResponseDataGmvTrendPerformances.attributeTypeMap;
    }
}

