/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Order202309GetOrderDetailResponseDataOrdersLineItemsUnboxingCaseList {
    /**
    * Unboxed sku code associated with the actual unboxed item.
    */
    'unboxSku'?: string;
    /**
    * Indicates if the unboxed sku is a gift item Enumerations: NORMAL or GIFT
    */
    'unboxSkuType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "unboxSku",
            "baseName": "unbox_sku",
            "type": "string"
        },
        {
            "name": "unboxSkuType",
            "baseName": "unbox_sku_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Order202309GetOrderDetailResponseDataOrdersLineItemsUnboxingCaseList.attributeTypeMap;
    }
}

