/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202608GetInboxCategoryCountsResponseDataDataGroupCounts } from './GetInboxCategoryCountsResponseDataDataGroupCounts';

export class AffiliateSeller202608GetInboxCategoryCountsResponseDataData {
    /**
    * List of different IM group
    */
    'groupCounts'?: Array<AffiliateSeller202608GetInboxCategoryCountsResponseDataDataGroupCounts>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "groupCounts",
            "baseName": "group_counts",
            "type": "Array<AffiliateSeller202608GetInboxCategoryCountsResponseDataDataGroupCounts>"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202608GetInboxCategoryCountsResponseDataData.attributeTypeMap;
    }
}

