/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202608GetInboxCategoryCountsResponseDataData } from './GetInboxCategoryCountsResponseDataData';

export class AffiliateSeller202608GetInboxCategoryCountsResponseData {
    'data'?: AffiliateSeller202608GetInboxCategoryCountsResponseDataData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "AffiliateSeller202608GetInboxCategoryCountsResponseDataData"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202608GetInboxCategoryCountsResponseData.attributeTypeMap;
    }
}

