/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202608GetInboxCategoryCountsResponseDataDataGroupCounts {
    /**
    * Conversation count in this group
    */
    'count'?: number;
    /**
    * Group type name, e.g. - UNREAD -UNREPLIED -STARRED -ARCHIVED
    */
    'groupType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "groupType",
            "baseName": "group_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202608GetInboxCategoryCountsResponseDataDataGroupCounts.attributeTypeMap;
    }
}

