/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar } from './GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorAvgCommissionRateRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorAvgCommissionRateRange';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyer } from './GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyer';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyerRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyerRange';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorCategoryGmvDistribution } from './GetMarketplaceCreatorPerformanceResponseDataCreatorCategoryGmvDistribution';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorContentGmvDistribution } from './GetMarketplaceCreatorPerformanceResponseDataCreatorContentGmvDistribution';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorCreatorProfile } from './GetMarketplaceCreatorPerformanceResponseDataCreatorCreatorProfile';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorFollowerAge } from './GetMarketplaceCreatorPerformanceResponseDataCreatorFollowerAge';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorFollowerGender } from './GetMarketplaceCreatorPerformanceResponseDataCreatorFollowerGender';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorFollowerLocation } from './GetMarketplaceCreatorPerformanceResponseDataCreatorFollowerLocation';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorGmv } from './GetMarketplaceCreatorPerformanceResponseDataCreatorGmv';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorGmvRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorGmvRange';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorGpm } from './GetMarketplaceCreatorPerformanceResponseDataCreatorGpm';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGmv } from './GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGmv';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpm } from './GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpm';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpmRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpmRange';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorProductOriginalPriceRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorProductOriginalPriceRange';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorUnitsSoldRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorUnitsSoldRange';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGmv } from './GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGmv';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpm } from './GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpm';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpmRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpmRange';

export class AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreator {
    'avatar'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar;
    /**
    * The average commission rate in hundredths of a percent. Note that if the creator has not given permission for precise data sharing, these properties will not be present.
    */
    'avgCommissionRate'?: number;
    'avgCommissionRateRange'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorAvgCommissionRateRange;
    /**
    * Average e-commerce live stream comments.
    */
    'avgEcLiveCommentCount'?: number;
    /**
    * Average e-commerce live stream likes.
    */
    'avgEcLiveLikeCount'?: number;
    /**
    * Average e-commerce live stream shares.
    */
    'avgEcLiveShareCount'?: number;
    /**
    * Average live stream views with promoted products.
    */
    'avgEcLiveViewCount'?: number;
    /**
    * Average e-commerce video comments.
    */
    'avgEcVideoCommentCount'?: number;
    /**
    * Average e-commerce video likes.
    */
    'avgEcVideoLikeCount'?: number;
    /**
    * The average number of number of e-commerce video plays. 
    */
    'avgEcVideoPlayCount'?: number;
    /**
    * Average e-commerce video shares.
    */
    'avgEcVideoShareCount'?: number;
    'avgGmvPerBuyer'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyer;
    'avgGmvPerBuyerRange'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyerRange;
    /**
    * The biography description associated with the creator.
    */
    'bioDescription'?: string;
    /**
    * The total number of brands with which the creator has previously collaborated.
    */
    'brandCollaborationCount'?: number;
    /**
    * GMV distribution by category.
    */
    'categoryGmvDistribution'?: Array<AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorCategoryGmvDistribution>;
    /**
    * A list of category identifiers associated with the products for which the creator has created posts. 
    */
    'categoryIds'?: Array<string>;
    /**
    * GMV associated with creator content by content type.
    */
    'contentGmvDistribution'?: Array<AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorContentGmvDistribution>;
    'creatorProfile'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorCreatorProfile;
    /**
    * The number of e-commerce livestreams associated with the creator.
    */
    'ecLiveCount'?: number;
    /**
    * E-commerce live stream engagement rate in hundredths of a percent. For example, `6000` is 60%.
    */
    'ecLiveEngagementRate'?: string;
    /**
    * The number of e-commerce video posts associated with the creator.
    */
    'ecVideoCount'?: number;
    /**
    * The number of post engagements (likes, shares, and comments) divided by the total video views averaged across the videos in the last 30 days. For example, 3000 stands for 0.3 or 30%
    */
    'ecVideoEngagementRate'?: string;
    /**
    * A list of key–value pairs representing the distribution of followers by age range.
    */
    'followerAge'?: Array<AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorFollowerAge>;
    /**
    * The creator\'s follower count.
    */
    'followerCount'?: number;
    /**
    * A list of key–value pairs representing the distribution of followers by gender.
    */
    'followerGender'?: Array<AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorFollowerGender>;
    /**
    * A list of key–value pairs representing the distribution of followers by location.
    */
    'followerLocation'?: Array<AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorFollowerLocation>;
    'gmv'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorGmv;
    'gmvRange'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorGmvRange;
    'gpm'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorGpm;
    'gpmRange'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange;
    'liveGmv'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGmv;
    'liveGpm'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpm;
    'liveGpmRange'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpmRange;
    /**
    * TikTok nickname.
    */
    'nickname'?: string;
    /**
    * The projected rate at which a creator is likely to post a shoppable video or LIVE after receiving a sample. For example, 3000 stands for 0.3 or 30%
    */
    'postRate'?: string;
    /**
    * Promotion Performance Score (PPS) The score reflects the quality of a creator\'s shoppable content and product selection over the past 90 days. A high score may indicate a better shopping experience, with fewer potential refunds or negative reviews.
    */
    'pps'?: string;
    'productOriginalPriceRange'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorProductOriginalPriceRange;
    /**
    * The URL for the creator\'s TikTok profile page.
    */
    'profileTtUri'?: string;
    /**
    * The number of promoted products associated with the creator. 
    */
    'promotedProductNum'?: number;
    /**
    * Rating from sellers who worked with this creator
    */
    'rating'?: string;
    /**
    * The region associated with the creator.
    */
    'selectionRegion'?: string;
    /**
    * A list of the top 10 brands with which the creator has previously collaborated.
    */
    'topCollaboratedBrandIds'?: Array<string>;
    /**
    * The total number of units sold. Units are indexed to SKU. Note that if the creator has not given permission for precise data sharing, this property will not be present.
    */
    'unitsSold'?: number;
    'unitsSoldRange'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorUnitsSoldRange;
    /**
    * TikTok user name.
    */
    'username'?: string;
    'videoGmv'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGmv;
    'videoGpm'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpm;
    'videoGpmRange'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpmRange;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar"
        },
        {
            "name": "avgCommissionRate",
            "baseName": "avg_commission_rate",
            "type": "number"
        },
        {
            "name": "avgCommissionRateRange",
            "baseName": "avg_commission_rate_range",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorAvgCommissionRateRange"
        },
        {
            "name": "avgEcLiveCommentCount",
            "baseName": "avg_ec_live_comment_count",
            "type": "number"
        },
        {
            "name": "avgEcLiveLikeCount",
            "baseName": "avg_ec_live_like_count",
            "type": "number"
        },
        {
            "name": "avgEcLiveShareCount",
            "baseName": "avg_ec_live_share_count",
            "type": "number"
        },
        {
            "name": "avgEcLiveViewCount",
            "baseName": "avg_ec_live_view_count",
            "type": "number"
        },
        {
            "name": "avgEcVideoCommentCount",
            "baseName": "avg_ec_video_comment_count",
            "type": "number"
        },
        {
            "name": "avgEcVideoLikeCount",
            "baseName": "avg_ec_video_like_count",
            "type": "number"
        },
        {
            "name": "avgEcVideoPlayCount",
            "baseName": "avg_ec_video_play_count",
            "type": "number"
        },
        {
            "name": "avgEcVideoShareCount",
            "baseName": "avg_ec_video_share_count",
            "type": "number"
        },
        {
            "name": "avgGmvPerBuyer",
            "baseName": "avg_gmv_per_buyer",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyer"
        },
        {
            "name": "avgGmvPerBuyerRange",
            "baseName": "avg_gmv_per_buyer_range",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyerRange"
        },
        {
            "name": "bioDescription",
            "baseName": "bio_description",
            "type": "string"
        },
        {
            "name": "brandCollaborationCount",
            "baseName": "brand_collaboration_count",
            "type": "number"
        },
        {
            "name": "categoryGmvDistribution",
            "baseName": "category_gmv_distribution",
            "type": "Array<AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorCategoryGmvDistribution>"
        },
        {
            "name": "categoryIds",
            "baseName": "category_ids",
            "type": "Array<string>"
        },
        {
            "name": "contentGmvDistribution",
            "baseName": "content_gmv_distribution",
            "type": "Array<AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorContentGmvDistribution>"
        },
        {
            "name": "creatorProfile",
            "baseName": "creator_profile",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorCreatorProfile"
        },
        {
            "name": "ecLiveCount",
            "baseName": "ec_live_count",
            "type": "number"
        },
        {
            "name": "ecLiveEngagementRate",
            "baseName": "ec_live_engagement_rate",
            "type": "string"
        },
        {
            "name": "ecVideoCount",
            "baseName": "ec_video_count",
            "type": "number"
        },
        {
            "name": "ecVideoEngagementRate",
            "baseName": "ec_video_engagement_rate",
            "type": "string"
        },
        {
            "name": "followerAge",
            "baseName": "follower_age",
            "type": "Array<AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorFollowerAge>"
        },
        {
            "name": "followerCount",
            "baseName": "follower_count",
            "type": "number"
        },
        {
            "name": "followerGender",
            "baseName": "follower_gender",
            "type": "Array<AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorFollowerGender>"
        },
        {
            "name": "followerLocation",
            "baseName": "follower_location",
            "type": "Array<AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorFollowerLocation>"
        },
        {
            "name": "gmv",
            "baseName": "gmv",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorGmv"
        },
        {
            "name": "gmvRange",
            "baseName": "gmv_range",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorGmvRange"
        },
        {
            "name": "gpm",
            "baseName": "gpm",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorGpm"
        },
        {
            "name": "gpmRange",
            "baseName": "gpm_range",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange"
        },
        {
            "name": "liveGmv",
            "baseName": "live_gmv",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGmv"
        },
        {
            "name": "liveGpm",
            "baseName": "live_gpm",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpm"
        },
        {
            "name": "liveGpmRange",
            "baseName": "live_gpm_range",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpmRange"
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string"
        },
        {
            "name": "postRate",
            "baseName": "post_rate",
            "type": "string"
        },
        {
            "name": "pps",
            "baseName": "pps",
            "type": "string"
        },
        {
            "name": "productOriginalPriceRange",
            "baseName": "product_original_price_range",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorProductOriginalPriceRange"
        },
        {
            "name": "profileTtUri",
            "baseName": "profile_tt_uri",
            "type": "string"
        },
        {
            "name": "promotedProductNum",
            "baseName": "promoted_product_num",
            "type": "number"
        },
        {
            "name": "rating",
            "baseName": "rating",
            "type": "string"
        },
        {
            "name": "selectionRegion",
            "baseName": "selection_region",
            "type": "string"
        },
        {
            "name": "topCollaboratedBrandIds",
            "baseName": "top_collaborated_brand_ids",
            "type": "Array<string>"
        },
        {
            "name": "unitsSold",
            "baseName": "units_sold",
            "type": "number"
        },
        {
            "name": "unitsSoldRange",
            "baseName": "units_sold_range",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorUnitsSoldRange"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        },
        {
            "name": "videoGmv",
            "baseName": "video_gmv",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGmv"
        },
        {
            "name": "videoGpm",
            "baseName": "video_gpm",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpm"
        },
        {
            "name": "videoGpmRange",
            "baseName": "video_gpm_range",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpmRange"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreator.attributeTypeMap;
    }
}

