/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorCreatorProfileCreatorConnectInfo {
    /**
    * Creator is blocked or not
    */
    'isBlocked'?: boolean;
    /**
    * Creator is connect or not
    */
    'isConnect'?: boolean;
    /**
    * Creator is paired or not
    */
    'isPaired'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isBlocked",
            "baseName": "is_blocked",
            "type": "boolean"
        },
        {
            "name": "isConnect",
            "baseName": "is_connect",
            "type": "boolean"
        },
        {
            "name": "isPaired",
            "baseName": "is_paired",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreatorCreatorProfileCreatorConnectInfo.attributeTypeMap;
    }
}

