/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreator } from './GetMarketplaceCreatorPerformanceResponseDataCreator';

export class AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseData {
    'creator'?: AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreator;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "creator",
            "baseName": "creator",
            "type": "AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseDataCreator"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202608GetMarketplaceCreatorPerformanceResponseData.attributeTypeMap;
    }
}

