/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202608GetSellerSearchCreatorMarketplaceAdvancedFiltersRequestBodyOptions {
    /**
    * Option type name, e.g. -OPTION_VERTICAL_PRO: Category Pro is a specific label given to Creators that regularly post about one product category and have generated most of their sales in that Category in the past 60 days -OPTION_LANGUAGE:  The language of the user -OPTION_CREATOR_LEVEL: The Creator level, based on their GMV. The exact definition changes by country, and is set by the TikTok Shop Creator team. -OPTION_SORTER: The creator search result sort algorithm. -OPTION_BRAND: Creator Brand info.
    */
    'optionType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "optionType",
            "baseName": "option_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202608GetSellerSearchCreatorMarketplaceAdvancedFiltersRequestBodyOptions.attributeTypeMap;
    }
}

