/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202608GetSellerSearchCreatorMarketplaceAdvancedFiltersResponseDataDataOptionListOptionsOptionChildren } from './GetSellerSearchCreatorMarketplaceAdvancedFiltersResponseDataDataOptionListOptionsOptionChildren';

export class AffiliateSeller202608GetSellerSearchCreatorMarketplaceAdvancedFiltersResponseDataDataOptionListOptions {
    /**
    * Option id
    */
    'id'?: string;
    /**
    * Option id
    */
    'name'?: string;
    /**
    * Children option detail list, used if the option has sub option choices
    */
    'optionChildren'?: Array<AffiliateSeller202608GetSellerSearchCreatorMarketplaceAdvancedFiltersResponseDataDataOptionListOptionsOptionChildren>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "optionChildren",
            "baseName": "option_children",
            "type": "Array<AffiliateSeller202608GetSellerSearchCreatorMarketplaceAdvancedFiltersResponseDataDataOptionListOptionsOptionChildren>"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202608GetSellerSearchCreatorMarketplaceAdvancedFiltersResponseDataDataOptionListOptions.attributeTypeMap;
    }
}

