/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202608GetWeeklyCreatorOutreachRecordsResponseDataDataConnectList } from './GetWeeklyCreatorOutreachRecordsResponseDataDataConnectList';

export class AffiliateSeller202608GetWeeklyCreatorOutreachRecordsResponseDataData {
    /**
    * Return the list of newly connected creator records for the shop
    */
    'connectList'?: Array<AffiliateSeller202608GetWeeklyCreatorOutreachRecordsResponseDataDataConnectList>;
    /**
    * Total count of record
    */
    'total'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "connectList",
            "baseName": "connect_list",
            "type": "Array<AffiliateSeller202608GetWeeklyCreatorOutreachRecordsResponseDataDataConnectList>"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202608GetWeeklyCreatorOutreachRecordsResponseDataData.attributeTypeMap;
    }
}

