/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202608GetWeeklyCreatorOutreachRecordsRequestBody {
    /**
    * Page index, need > 0
    */
    'pageIndex'?: number;
    /**
    * Page size, need > 1 and < =50
    */
    'pageSize'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pageIndex",
            "baseName": "page_index",
            "type": "number"
        },
        {
            "name": "pageSize",
            "baseName": "page_size",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202608GetWeeklyCreatorOutreachRecordsRequestBody.attributeTypeMap;
    }
}

