/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202608QueryCreatorPromotionDetailsinTargetCollaborationRequestBodyProductFilter } from './QueryCreatorPromotionDetailsinTargetCollaborationRequestBodyProductFilter';

export class AffiliateSeller202608QueryCreatorPromotionDetailsinTargetCollaborationRequestBody {
    /**
    * Creator open id
    */
    'creatorUserOpenId'?: string;
    /**
    * Invitation Group Id
    */
    'invitationGroupId'?: string;
    /**
    * Creator Invitation Id 
    */
    'invitationId'?: string;
    'productFilter'?: AffiliateSeller202608QueryCreatorPromotionDetailsinTargetCollaborationRequestBodyProductFilter;
    /**
    * Query value
    */
    'query'?: string;
    /**
    * Query type, e.g. - PRODUCT_ID: query by product id -PRODUCT_NAME: query by product name
    */
    'queryType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "creatorUserOpenId",
            "baseName": "creator_user_open_id",
            "type": "string"
        },
        {
            "name": "invitationGroupId",
            "baseName": "invitation_group_id",
            "type": "string"
        },
        {
            "name": "invitationId",
            "baseName": "invitation_id",
            "type": "string"
        },
        {
            "name": "productFilter",
            "baseName": "product_filter",
            "type": "AffiliateSeller202608QueryCreatorPromotionDetailsinTargetCollaborationRequestBodyProductFilter"
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "string"
        },
        {
            "name": "queryType",
            "baseName": "query_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202608QueryCreatorPromotionDetailsinTargetCollaborationRequestBody.attributeTypeMap;
    }
}

