/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202608SellerSearchCreatoronMarketplaceResponseDataCreatorsCreatorProfile {
    /**
    * Creator bind MCN name
    */
    'creatorBindMcnName'?: string;
    /**
    * Creator level
    */
    'creatorLevel'?: number;
    /**
    * Has collaborated with this creator or not
    */
    'hasCollaborated'?: boolean;
    /**
    * Has invited creaor before 90 days
    */
    'hasInvited90d'?: boolean;
    /**
    * Is this creator blocked by shop or not
    */
    'isCreatorBlocked'?: boolean;
    /**
    * Is creator eligible for flat fee, only available for US local seller
    */
    'isEligibleFlatFee'?: boolean;
    /**
    * Creator has fast growing tag or not
    */
    'isFastGrowing'?: boolean;
    /**
    * Creator has official recommend tag or not
    */
    'isOfficialRecommend'?: boolean;
    /**
    * Creator has rising star tag or not
    */
    'isRisingStar'?: boolean;
    /**
    * Creator promotion performance score(PPS).The score reflects the quality of a creator\'s shoppable content and product selection over the past 30 days. A high score may indicate a better shopping experience, with fewer potential refunds or negative reviews. e.g. 4.3/5.0
    */
    'ppsScore'?: string;
    /**
    * User type tag. -1 privacy creator -2 carve out creator
    */
    'userTypeTag'?: Array<number>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "creatorBindMcnName",
            "baseName": "creator_bind_mcn_name",
            "type": "string"
        },
        {
            "name": "creatorLevel",
            "baseName": "creator_level",
            "type": "number"
        },
        {
            "name": "hasCollaborated",
            "baseName": "has_collaborated",
            "type": "boolean"
        },
        {
            "name": "hasInvited90d",
            "baseName": "has_invited_90d",
            "type": "boolean"
        },
        {
            "name": "isCreatorBlocked",
            "baseName": "is_creator_blocked",
            "type": "boolean"
        },
        {
            "name": "isEligibleFlatFee",
            "baseName": "is_eligible_flat_fee",
            "type": "boolean"
        },
        {
            "name": "isFastGrowing",
            "baseName": "is_fast_growing",
            "type": "boolean"
        },
        {
            "name": "isOfficialRecommend",
            "baseName": "is_official_recommend",
            "type": "boolean"
        },
        {
            "name": "isRisingStar",
            "baseName": "is_rising_star",
            "type": "boolean"
        },
        {
            "name": "ppsScore",
            "baseName": "pps_score",
            "type": "string"
        },
        {
            "name": "userTypeTag",
            "baseName": "user_type_tag",
            "type": "Array<number>"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202608SellerSearchCreatoronMarketplaceResponseDataCreatorsCreatorProfile.attributeTypeMap;
    }
}

