/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Promotion202607RepublishActivityRequestBody {
    /**
    * Activity start time. UNIX timestamp. The value must be greater than the value of the current time.
    */
    'beginTime'?: number;
    /**
    * Activity end time. UNIX timestamp.
    */
    'endTime'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "beginTime",
            "baseName": "begin_time",
            "type": "number"
        },
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Promotion202607RepublishActivityRequestBody.attributeTypeMap;
    }
}

