/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Promotion202607RepublishActivityResponseData {
    /**
    * A unique ID that identifies different activities.
    */
    'activityId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "activityId",
            "baseName": "activity_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Promotion202607RepublishActivityResponseData.attributeTypeMap;
    }
}

