/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Promotion202406SearchCouponListResponseDataCouponsDiscountMaxDiscount } from './SearchCouponListResponseDataCouponsDiscountMaxDiscount';
import { Promotion202406SearchCouponListResponseDataCouponsDiscountReductionAmount } from './SearchCouponListResponseDataCouponsDiscountReductionAmount';

export class Promotion202406SearchCouponListResponseDataCouponsDiscount {
    'maxDiscount'?: Promotion202406SearchCouponListResponseDataCouponsDiscountMaxDiscount;
    /**
    * The discount offered by the coupon, in percentage points. Will appear when `type == \'PERCENT_OFF\'`.
    */
    'percentage'?: string;
    'reductionAmount'?: Promotion202406SearchCouponListResponseDataCouponsDiscountReductionAmount;
    /**
    * The type of discount offered by the coupon. Possible enumerations are: - `AMOUNT_OFF`: Reduces the final price of the item by the specified `reduction_amount` - `PERCENT_OFF`: Reduces the final price by the specified `percentage`.
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "maxDiscount",
            "baseName": "max_discount",
            "type": "Promotion202406SearchCouponListResponseDataCouponsDiscountMaxDiscount"
        },
        {
            "name": "percentage",
            "baseName": "percentage",
            "type": "string"
        },
        {
            "name": "reductionAmount",
            "baseName": "reduction_amount",
            "type": "Promotion202406SearchCouponListResponseDataCouponsDiscountReductionAmount"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Promotion202406SearchCouponListResponseDataCouponsDiscount.attributeTypeMap;
    }
}

