/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202606GetProductSKPPDetailResponseDataRewardsClaimConditions } from './GetProductSKPPDetailResponseDataRewardsClaimConditions';

export class Product202606GetProductSKPPDetailResponseDataRewards {
    /**
    * Ad-credit-only sub-status, returned only when reward_type = ADS_CREDIT and status = AVAILABLE. Possible values: UNCLAIMED (eligible, not yet claimed) / CLAIMED (claimed).
    */
    'adCreditClaimStatus'?: string;
    /**
    * Returned only for reward_type = BIG_PROMOTION_CAMPAIGN.
    */
    'campaignId'?: string;
    /**
    * Thresholds to unlock the reward; used by ADS_CREDIT.
    */
    'claimConditions'?: Array<Product202606GetProductSKPPDetailResponseDataRewardsClaimConditions>;
    /**
    * Possible values: ADS_CREDIT / TOP_CREATOR_MATCHMAKING / SHOPTAB_PV / BIG_PROMOTION_CAMPAIGN.
    */
    'rewardType'?: string;
    /**
    * Possible values: NOT_GRANTED / PENDING / AVAILABLE
    */
    'status'?: string;
    /**
    * Localized reward name, resolved from the shared Seller-Center content by the request locale.
    */
    'title'?: string;
    /**
    * Granted amount/quantity; currency-typed values lead with the currency symbol.
    */
    'value'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "adCreditClaimStatus",
            "baseName": "ad_credit_claim_status",
            "type": "string"
        },
        {
            "name": "campaignId",
            "baseName": "campaign_id",
            "type": "string"
        },
        {
            "name": "claimConditions",
            "baseName": "claim_conditions",
            "type": "Array<Product202606GetProductSKPPDetailResponseDataRewardsClaimConditions>"
        },
        {
            "name": "rewardType",
            "baseName": "reward_type",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202606GetProductSKPPDetailResponseDataRewards.attributeTypeMap;
    }
}

