/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202606GetProductSKPPDetailResponseDataRewardsClaimConditions {
    /**
    * Possible values: GMV / ORDER.
    */
    'conditionType'?: string;
    /**
    * Current progress; GMV-typed values lead with the currency symbol.
    */
    'currentValue'?: string;
    /**
    * Threshold value; same formatting as current_value.
    */
    'targetValue'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "conditionType",
            "baseName": "condition_type",
            "type": "string"
        },
        {
            "name": "currentValue",
            "baseName": "current_value",
            "type": "string"
        },
        {
            "name": "targetValue",
            "baseName": "target_value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202606GetProductSKPPDetailResponseDataRewardsClaimConditions.attributeTypeMap;
    }
}

