/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202606GetProductSKPPDetailResponseDataRewards } from './GetProductSKPPDetailResponseDataRewards';
import { Product202606GetProductSKPPDetailResponseDataTaskDetails } from './GetProductSKPPDetailResponseDataTaskDetails';

export class Product202606GetProductSKPPDetailResponseData {
    /**
    * Affiliate Program enrolment. Possible values: ACTIVE / INACTIVE.
    */
    'affiliateProgramStatus'?: string;
    /**
    * Platform product ID.
    */
    'productId'?: string;
    /**
    * Reward list.
    */
    'rewards'?: Array<Product202606GetProductSKPPDetailResponseDataRewards>;
    /**
    * Possible values: QUALIFIED / NOT_QUALIFIED / NOT_ELIGIBLE.
    */
    'skppStatus'?: string;
    /**
    * Score threshold to qualify for SKPP.
    */
    'targetScore'?: number;
    /**
    * Per-category score breakdown with suggested actions.
    */
    'taskDetails'?: Array<Product202606GetProductSKPPDetailResponseDataTaskDetails>;
    /**
    * Current SKPP total score, as of update_time.
    */
    'totalScore'?: number;
    /**
    * Date of the offline data snapshot that total_score, rewards and the score breakdown are derived from, returned as a Unix timestamp in seconds, pinned to the last second of that date in UTC (23:59:59Z). The value is date-level only — the time component is always 23:59:59 UTC — because the SKPP scoring runs in an offline pipeline with no intraday granularity. Latency is typically T+1 (the evening of day N publishes the day N−1 snapshot) and at most T+2.
    */
    'updateTime'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "affiliateProgramStatus",
            "baseName": "affiliate_program_status",
            "type": "string"
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        },
        {
            "name": "rewards",
            "baseName": "rewards",
            "type": "Array<Product202606GetProductSKPPDetailResponseDataRewards>"
        },
        {
            "name": "skppStatus",
            "baseName": "skpp_status",
            "type": "string"
        },
        {
            "name": "targetScore",
            "baseName": "target_score",
            "type": "number"
        },
        {
            "name": "taskDetails",
            "baseName": "task_details",
            "type": "Array<Product202606GetProductSKPPDetailResponseDataTaskDetails>"
        },
        {
            "name": "totalScore",
            "baseName": "total_score",
            "type": "number"
        },
        {
            "name": "updateTime",
            "baseName": "update_time",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Product202606GetProductSKPPDetailResponseData.attributeTypeMap;
    }
}

