/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202606GetProductSKPPDetailResponseDataTaskDetailsActionSuggestions {
    /**
    * SKPP points added to total_score when this action is completed; for tiered actions, the maximum tier.
    */
    'scoreIncrease'?: number;
    /**
    * Link to the Seller Center page that completes the action.
    */
    'url'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "scoreIncrease",
            "baseName": "score_increase",
            "type": "number"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202606GetProductSKPPDetailResponseDataTaskDetailsActionSuggestions.attributeTypeMap;
    }
}

