/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202606ListProductsSKPPStatusResponseDataProductsRewards {
    /**
    * Ad-credit-only sub-status, returned only when reward_type = ADS_CREDIT and status = AVAILABLE. Possible values: UNCLAIMED (eligible, not yet claimed) / CLAIMED (claimed). Ad credit must be claimed manually.
    */
    'adCreditClaimStatus'?: string;
    /**
    * Possible values: ADS_CREDIT / TOP_CREATOR_MATCHMAKING / SHOPTAB_PV.
    */
    'rewardType'?: string;
    /**
    * Possible values: NOT_GRANTED (below threshold, locked) / PENDING (qualified, not yet granted) / AVAILABLE (granted).
    */
    'status'?: string;
    /**
    * Granted amount/quantity; present only when status = AVAILABLE. Currency-typed (ADS_CREDIT) leads with the currency symbol (e.g. $15); count-typed (TOP_CREATOR_MATCHMAKING, SHOPTAB_PV) are bare numbers.
    */
    'value'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "adCreditClaimStatus",
            "baseName": "ad_credit_claim_status",
            "type": "string"
        },
        {
            "name": "rewardType",
            "baseName": "reward_type",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202606ListProductsSKPPStatusResponseDataProductsRewards.attributeTypeMap;
    }
}

