/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202606ListProductsSKPPStatusRequestBody {
    /**
    * page no 
    */
    'pageNo'?: number;
    /**
    * Page number, starts at 1; used with page_size.
    */
    'pageSize'?: number;
    /**
    * Product IDs generated by Tiktok Shop; up to 100 per call. 
    */
    'productIds'?: Array<string>;
    /**
    * Optional filter.  Possible values:QUALIFIED (already an SKPP product) / NOT_QUALIFIED (not yet meeting the standard, but eligible to take SKPP tasks).
    */
    'skppStatus'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pageNo",
            "baseName": "page_no",
            "type": "number"
        },
        {
            "name": "pageSize",
            "baseName": "page_size",
            "type": "number"
        },
        {
            "name": "productIds",
            "baseName": "product_ids",
            "type": "Array<string>"
        },
        {
            "name": "skppStatus",
            "baseName": "skpp_status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202606ListProductsSKPPStatusRequestBody.attributeTypeMap;
    }
}

