/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202604SubmitAppealTaskRequestBodyAppealMessageIndicatorDetails {
    /**
    * The target indicator_type to appeal of this field. Possible values: - REQUIRED_DIMENSION：Does the size chart include all required dimensions? - CONTAINS_ALL_SALE_PROPERTY：Does the size chart cover all sales attributes?\"\" - VALUE_RANGE_OUT_OF_RANGE：Are the value ranges in the size chart valid?
    */
    'indicatorType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "indicatorType",
            "baseName": "indicator_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202604SubmitAppealTaskRequestBodyAppealMessageIndicatorDetails.attributeTypeMap;
    }
}

