/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202604SubmitAppealTaskRequestBodyAppealMessageIndicatorDetails } from './SubmitAppealTaskRequestBodyAppealMessageIndicatorDetails';

export class Product202604SubmitAppealTaskRequestBodyAppealMessage {
    /**
    * The target fields to appeal. Possible values: - APPEAL_MESSAGE_FIELD_SIZE_CHART
    */
    'fieldName'?: string;
    /**
    * Indicator details of the products submitted for appeal
    */
    'indicatorDetails'?: Array<Product202604SubmitAppealTaskRequestBodyAppealMessageIndicatorDetails>;
    /**
    * size_chart_id
    */
    'sizeChartId'?: string;
    /**
    * uri of size_chart_image
    */
    'sizeChartImageUri'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fieldName",
            "baseName": "field_name",
            "type": "string"
        },
        {
            "name": "indicatorDetails",
            "baseName": "indicator_details",
            "type": "Array<Product202604SubmitAppealTaskRequestBodyAppealMessageIndicatorDetails>"
        },
        {
            "name": "sizeChartId",
            "baseName": "size_chart_id",
            "type": "string"
        },
        {
            "name": "sizeChartImageUri",
            "baseName": "size_chart_image_uri",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202604SubmitAppealTaskRequestBodyAppealMessage.attributeTypeMap;
    }
}

