/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202604UpdateStockOperationSettingsResponseDataStockOperation } from './UpdateStockOperationSettingsResponseDataStockOperation';

export class Product202604UpdateStockOperationSettingsResponseData {
    'stockOperation'?: Product202604UpdateStockOperationSettingsResponseDataStockOperation;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "stockOperation",
            "baseName": "stock_operation",
            "type": "Product202604UpdateStockOperationSettingsResponseDataStockOperation"
        }    ];

    static getAttributeTypeMap() {
        return Product202604UpdateStockOperationSettingsResponseData.attributeTypeMap;
    }
}

