/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateCreator202607TokoProductMapperV2ResponseDataProduct {
    /**
    * product id in tokopedia format
    */
    'tokoPid'?: number;
    /**
    * product id in tts format
    */
    'ttsPid'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tokoPid",
            "baseName": "toko_pid",
            "type": "number"
        },
        {
            "name": "ttsPid",
            "baseName": "tts_pid",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202607TokoProductMapperV2ResponseDataProduct.attributeTypeMap;
    }
}

