/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateCreator202607TokoProductMapperV2ResponseDataError } from './TokoProductMapperV2ResponseDataError';
import { AffiliateCreator202607TokoProductMapperV2ResponseDataProduct } from './TokoProductMapperV2ResponseDataProduct';

export class AffiliateCreator202607TokoProductMapperV2ResponseData {
    'error'?: AffiliateCreator202607TokoProductMapperV2ResponseDataError;
    /**
    * list of product data
    */
    'product'?: Array<AffiliateCreator202607TokoProductMapperV2ResponseDataProduct>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "AffiliateCreator202607TokoProductMapperV2ResponseDataError"
        },
        {
            "name": "product",
            "baseName": "product",
            "type": "Array<AffiliateCreator202607TokoProductMapperV2ResponseDataProduct>"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202607TokoProductMapperV2ResponseData.attributeTypeMap;
    }
}

