/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Fulfillment202607GetOrderCustomsRequirementsResponseDataOrderClearanceListItemList } from './GetOrderCustomsRequirementsResponseDataOrderClearanceListItemList';

export class Fulfillment202607GetOrderCustomsRequirementsResponseDataOrderClearanceList {
    /**
    * Whether an order alreay filled customs infomation
    */
    'alreadyFilledClearance'?: boolean;
    /**
    * enum CustomsBusinessType {     CustomsBusinessTypeFS = 1;     CustomsBusinessTypePOP = 2; }
    */
    'bizType'?: number;
    /**
    * The number of packages
    */
    'itemList'?: Array<Fulfillment202607GetOrderCustomsRequirementsResponseDataOrderClearanceListItemList>;
    /**
    * Whether an order needs to fill customs infomation: - true: The order needs to fill in customs information. - false: The order does not need to fill in custom information.
    */
    'needFillClearance'?: boolean;
    /**
    * TikTok Shop order ID
    */
    'orderId'?: string;
    /**
    * enum ShipmentType{     CROSS_BORDER = 1,     LOCAL = 2, }
    */
    'shipmentType'?: number;
    /**
    * Country Alpha-2 Code
    */
    'targetCountry'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "alreadyFilledClearance",
            "baseName": "already_filled_clearance",
            "type": "boolean"
        },
        {
            "name": "bizType",
            "baseName": "biz_type",
            "type": "number"
        },
        {
            "name": "itemList",
            "baseName": "item_list",
            "type": "Array<Fulfillment202607GetOrderCustomsRequirementsResponseDataOrderClearanceListItemList>"
        },
        {
            "name": "needFillClearance",
            "baseName": "need_fill_clearance",
            "type": "boolean"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        },
        {
            "name": "shipmentType",
            "baseName": "shipment_type",
            "type": "number"
        },
        {
            "name": "targetCountry",
            "baseName": "target_country",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Fulfillment202607GetOrderCustomsRequirementsResponseDataOrderClearanceList.attributeTypeMap;
    }
}

