/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Fulfillment202607UploadCustomsInfomationRequestBodyOrderList } from './UploadCustomsInfomationRequestBodyOrderList';

export class Fulfillment202607UploadCustomsInfomationRequestBody {
    /**
    * List of TikTok Shop clearance info
    */
    'orderList'?: Array<Fulfillment202607UploadCustomsInfomationRequestBodyOrderList>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderList",
            "baseName": "order_list",
            "type": "Array<Fulfillment202607UploadCustomsInfomationRequestBodyOrderList>"
        }    ];

    static getAttributeTypeMap() {
        return Fulfillment202607UploadCustomsInfomationRequestBody.attributeTypeMap;
    }
}

