/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Fulfillment202607UploadCustomsInfomationRequestBodyOrderListItemList } from './UploadCustomsInfomationRequestBodyOrderListItemList';

export class Fulfillment202607UploadCustomsInfomationRequestBodyOrderList {
    /**
    * clearance info list
    */
    'itemList'?: Array<Fulfillment202607UploadCustomsInfomationRequestBodyOrderListItemList>;
    /**
    * TikTok Shop order ID
    */
    'orderId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "itemList",
            "baseName": "item_list",
            "type": "Array<Fulfillment202607UploadCustomsInfomationRequestBodyOrderListItemList>"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Fulfillment202607UploadCustomsInfomationRequestBodyOrderList.attributeTypeMap;
    }
}

