/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Fulfillment202607UploadCustomsInfomationRequestBodyOrderListItemListItemDetail {
    /**
    * unit: %, price_percent=10 means 10%
    */
    'pricePercent'?: number;
    /**
    * The amount of this sku
    */
    'qty'?: number;
    /**
    * The percentage of the total of this order
    */
    'skuId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pricePercent",
            "baseName": "price_percent",
            "type": "number"
        },
        {
            "name": "qty",
            "baseName": "qty",
            "type": "number"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Fulfillment202607UploadCustomsInfomationRequestBodyOrderListItemListItemDetail.attributeTypeMap;
    }
}

