/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Fulfillment202607UploadCustomsInfomationRequestBodyOrderListItemListItemDetail } from './UploadCustomsInfomationRequestBodyOrderListItemListItemDetail';

export class Fulfillment202607UploadCustomsInfomationRequestBodyOrderListItemList {
    /**
    * item info releated to this sub order
    */
    'itemDetail'?: Array<Fulfillment202607UploadCustomsInfomationRequestBodyOrderListItemListItemDetail>;
    /**
    * Sub order ID; order_line_id and sku_id should not be both empty.
    */
    'orderLineId'?: string;
    /**
    * SKU ID; order_line_id and sku_id should not be both empty.
    */
    'skuId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "itemDetail",
            "baseName": "item_detail",
            "type": "Array<Fulfillment202607UploadCustomsInfomationRequestBodyOrderListItemListItemDetail>"
        },
        {
            "name": "orderLineId",
            "baseName": "order_line_id",
            "type": "string"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Fulfillment202607UploadCustomsInfomationRequestBodyOrderListItemList.attributeTypeMap;
    }
}

