/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202406SellerSearchCreatoronMarketplaceRequestBodyAdvancedFilters {
    /**
    * Supported creator levels are country/region-specific. Always fetch the valid creator level enums from the Get Seller Search [Creator Marketplace Advanced Filters](https://partner.tiktokshop.com/docv2/page/get-seller-search-creator-marketplace-advanced-filters-202601) endpoint before calling this API.
    */
    'creatorLevel'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "creatorLevel",
            "baseName": "creator_level",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202406SellerSearchCreatoronMarketplaceRequestBodyAdvancedFilters.attributeTypeMap;
    }
}

