/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversion } from './GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversion';
import { Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsInteractions } from './GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsInteractions';
import { Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsSales } from './GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsSales';
import { Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsTraffic } from './GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsTraffic';

export class Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervals {
    'conversion'?: Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversion;
    /**
    * End time of this interval, unix timestamp GMT (UTC+00:00).
    */
    'endTime'?: number;
    'interactions'?: Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsInteractions;
    'sales'?: Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsSales;
    /**
    * Start time of this interval, unix timestamp GMT (UTC+00:00).
    */
    'startTime'?: number;
    'traffic'?: Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsTraffic;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "conversion",
            "baseName": "conversion",
            "type": "Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversion"
        },
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "number"
        },
        {
            "name": "interactions",
            "baseName": "interactions",
            "type": "Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsInteractions"
        },
        {
            "name": "sales",
            "baseName": "sales",
            "type": "Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsSales"
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "number"
        },
        {
            "name": "traffic",
            "baseName": "traffic",
            "type": "Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsTraffic"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervals.attributeTypeMap;
    }
}

