/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversionAvgPrice } from './GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversionAvgPrice';
import { Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversionClickToOrderRate } from './GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversionClickToOrderRate';
import { Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversionGpm } from './GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversionGpm';

export class Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversion {
    'avgPrice'?: Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversionAvgPrice;
    'clickToOrderRate'?: Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversionClickToOrderRate;
    /**
    * The number of SKU orders created by users from the LIVE
    */
    'createdSkuOrders'?: number;
    'gpm'?: Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversionGpm;
    /**
    * Number of SKU orders from the LIVE divided by the impressions of the LIVE
    */
    'skuOrderRate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avgPrice",
            "baseName": "avg_price",
            "type": "Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversionAvgPrice"
        },
        {
            "name": "clickToOrderRate",
            "baseName": "click_to_order_rate",
            "type": "Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversionClickToOrderRate"
        },
        {
            "name": "createdSkuOrders",
            "baseName": "created_sku_orders",
            "type": "number"
        },
        {
            "name": "gpm",
            "baseName": "gpm",
            "type": "Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversionGpm"
        },
        {
            "name": "skuOrderRate",
            "baseName": "sku_order_rate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202510GetShopLIVEMinutePerformanceResponseDataPerformanceIntervalsConversion.attributeTypeMap;
    }
}

