/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202605GetShopProductPerformanceListResponseDataProductsAffiliateLivePerformanceLiveAttributedGmv } from './GetShopProductPerformanceListResponseDataProductsAffiliateLivePerformanceLiveAttributedGmv';

export class Analytics202605GetShopProductPerformanceListResponseDataProductsAffiliateLivePerformance {
    /**
    * Number of times products were added to cart from affiliate live.
    */
    'addCartCount'?: number;
    /**
    * Add to cart rate from affiliate live.
    */
    'addCartRate'?: string;
    /**
    * Number of users who added to cart from affiliate live.
    */
    'atcUsers'?: number;
    /**
    * Click to order rate from affiliate live.
    */
    'clickOrderRate'?: string;
    /**
    * Click-through rate from affiliate live.
    */
    'ctr'?: string;
    'liveAttributedGmv'?: Analytics202605GetShopProductPerformanceListResponseDataProductsAffiliateLivePerformanceLiveAttributedGmv;
    /**
    * Number of new live streams from affiliate.
    */
    'newLiveCount'?: number;
    /**
    * Product clicks from affiliate live.
    */
    'productClicks'?: number;
    /**
    * Product impressions from affiliate live.
    */
    'productImpressions'?: number;
    /**
    * Unique add to cart rate from affiliate live.
    */
    'uniqueAtcRate'?: string;
    /**
    * Unique click to order rate from affiliate live.
    */
    'uniqueClickOrderRate'?: string;
    /**
    * Unique clicks from affiliate live.
    */
    'uniqueClicks'?: number;
    /**
    * Unique click-through rate from affiliate live.
    */
    'uniqueCtr'?: string;
    /**
    * Unique product impressions from affiliate live.
    */
    'uniqueProductImpressions'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addCartCount",
            "baseName": "add_cart_count",
            "type": "number"
        },
        {
            "name": "addCartRate",
            "baseName": "add_cart_rate",
            "type": "string"
        },
        {
            "name": "atcUsers",
            "baseName": "atc_users",
            "type": "number"
        },
        {
            "name": "clickOrderRate",
            "baseName": "click_order_rate",
            "type": "string"
        },
        {
            "name": "ctr",
            "baseName": "ctr",
            "type": "string"
        },
        {
            "name": "liveAttributedGmv",
            "baseName": "live_attributed_gmv",
            "type": "Analytics202605GetShopProductPerformanceListResponseDataProductsAffiliateLivePerformanceLiveAttributedGmv"
        },
        {
            "name": "newLiveCount",
            "baseName": "new_live_count",
            "type": "number"
        },
        {
            "name": "productClicks",
            "baseName": "product_clicks",
            "type": "number"
        },
        {
            "name": "productImpressions",
            "baseName": "product_impressions",
            "type": "number"
        },
        {
            "name": "uniqueAtcRate",
            "baseName": "unique_atc_rate",
            "type": "string"
        },
        {
            "name": "uniqueClickOrderRate",
            "baseName": "unique_click_order_rate",
            "type": "string"
        },
        {
            "name": "uniqueClicks",
            "baseName": "unique_clicks",
            "type": "number"
        },
        {
            "name": "uniqueCtr",
            "baseName": "unique_ctr",
            "type": "string"
        },
        {
            "name": "uniqueProductImpressions",
            "baseName": "unique_product_impressions",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202605GetShopProductPerformanceListResponseDataProductsAffiliateLivePerformance.attributeTypeMap;
    }
}

