/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceAov } from './GetShopProductPerformanceListResponseDataProductsTotalPerformanceAov';
import { Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceGmv } from './GetShopProductPerformanceListResponseDataProductsTotalPerformanceGmv';
import { Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceGmvInclTax } from './GetShopProductPerformanceListResponseDataProductsTotalPerformanceGmvInclTax';
import { Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceGrossMerchandiseValue } from './GetShopProductPerformanceListResponseDataProductsTotalPerformanceGrossMerchandiseValue';
import { Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceRefunds } from './GetShopProductPerformanceListResponseDataProductsTotalPerformanceRefunds';
import { Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceShippingFees } from './GetShopProductPerformanceListResponseDataProductsTotalPerformanceShippingFees';
import { Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceTax } from './GetShopProductPerformanceListResponseDataProductsTotalPerformanceTax';

export class Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformance {
    /**
    * Number of times products were added to the cart.
    */
    'addCartCount'?: number;
    /**
    * Add to cart rate.
    */
    'addCartRate'?: string;
    /**
    * Number of users who added to cart.
    */
    'addCartUsers'?: number;
    'aov'?: Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceAov;
    /**
    * Click to order rate.
    */
    'clickOrderRate'?: string;
    /**
    * Click-through rate.
    */
    'ctr'?: string;
    /**
    * Estimated number of customers.
    */
    'estimatedCustomers'?: number;
    'gmv'?: Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceGmv;
    'gmvInclTax'?: Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceGmvInclTax;
    'grossMerchandiseValue'?: Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceGrossMerchandiseValue;
    /**
    * Number of items sold.
    */
    'itemsSold'?: number;
    /**
    * Number of orders.
    */
    'orders'?: number;
    /**
    * Number of product clicks.
    */
    'productClicks'?: number;
    /**
    * Number of product impressions.
    */
    'productImpressions'?: number;
    /**
    * Number of customers who received refunds.
    */
    'refundCustomers'?: number;
    /**
    * Number of items refunded.
    */
    'refundedItems'?: number;
    'refunds'?: Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceRefunds;
    'shippingFees'?: Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceShippingFees;
    /**
    * Number of SKU orders.
    */
    'skuOrders'?: number;
    'tax'?: Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceTax;
    /**
    * Unique add to cart rate.
    */
    'uniqueAtcRate'?: string;
    /**
    * Unique click to order rate.
    */
    'uniqueClickOrderRate'?: string;
    /**
    * Total number of unique product clicks across the product performance channels.
    */
    'uniqueClicks'?: number;
    /**
    * Unique click-through rate.
    */
    'uniqueCtr'?: string;
    /**
    * Unique product impressions.
    */
    'uniqueProductImpressions'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addCartCount",
            "baseName": "add_cart_count",
            "type": "number"
        },
        {
            "name": "addCartRate",
            "baseName": "add_cart_rate",
            "type": "string"
        },
        {
            "name": "addCartUsers",
            "baseName": "add_cart_users",
            "type": "number"
        },
        {
            "name": "aov",
            "baseName": "aov",
            "type": "Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceAov"
        },
        {
            "name": "clickOrderRate",
            "baseName": "click_order_rate",
            "type": "string"
        },
        {
            "name": "ctr",
            "baseName": "ctr",
            "type": "string"
        },
        {
            "name": "estimatedCustomers",
            "baseName": "estimated_customers",
            "type": "number"
        },
        {
            "name": "gmv",
            "baseName": "gmv",
            "type": "Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceGmv"
        },
        {
            "name": "gmvInclTax",
            "baseName": "gmv_incl_tax",
            "type": "Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceGmvInclTax"
        },
        {
            "name": "grossMerchandiseValue",
            "baseName": "gross_merchandise_value",
            "type": "Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceGrossMerchandiseValue"
        },
        {
            "name": "itemsSold",
            "baseName": "items_sold",
            "type": "number"
        },
        {
            "name": "orders",
            "baseName": "orders",
            "type": "number"
        },
        {
            "name": "productClicks",
            "baseName": "product_clicks",
            "type": "number"
        },
        {
            "name": "productImpressions",
            "baseName": "product_impressions",
            "type": "number"
        },
        {
            "name": "refundCustomers",
            "baseName": "refund_customers",
            "type": "number"
        },
        {
            "name": "refundedItems",
            "baseName": "refunded_items",
            "type": "number"
        },
        {
            "name": "refunds",
            "baseName": "refunds",
            "type": "Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceRefunds"
        },
        {
            "name": "shippingFees",
            "baseName": "shipping_fees",
            "type": "Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceShippingFees"
        },
        {
            "name": "skuOrders",
            "baseName": "sku_orders",
            "type": "number"
        },
        {
            "name": "tax",
            "baseName": "tax",
            "type": "Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformanceTax"
        },
        {
            "name": "uniqueAtcRate",
            "baseName": "unique_atc_rate",
            "type": "string"
        },
        {
            "name": "uniqueClickOrderRate",
            "baseName": "unique_click_order_rate",
            "type": "string"
        },
        {
            "name": "uniqueClicks",
            "baseName": "unique_clicks",
            "type": "number"
        },
        {
            "name": "uniqueCtr",
            "baseName": "unique_ctr",
            "type": "string"
        },
        {
            "name": "uniqueProductImpressions",
            "baseName": "unique_product_impressions",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202605GetShopProductPerformanceListResponseDataProductsTotalPerformance.attributeTypeMap;
    }
}

