/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202605GetShopProductPerformanceListResponseDataProductsShopTabPerformanceShopTabGmv } from './GetShopProductPerformanceListResponseDataProductsShopTabPerformanceShopTabGmv';

export class Analytics202605GetShopProductPerformanceListResponseDataProductsShopTabPerformance {
    /**
    * Estimated number of customers from Shop Tab.
    */
    'estimatedShopTabCustomers'?: number;
    /**
    * Click-to-order rate (SKU level) from Shop Tab.
    */
    'shopTabCtorSku'?: string;
    /**
    * Click-through rate from Shop Tab.
    */
    'shopTabCtr'?: string;
    'shopTabGmv'?: Analytics202605GetShopProductPerformanceListResponseDataProductsShopTabPerformanceShopTabGmv;
    /**
    * Number of product clicks from Shop Tab.
    */
    'shopTabProductClicks'?: number;
    /**
    * Number of product impressions from Shop Tab.
    */
    'shopTabProductImpressions'?: number;
    /**
    * Items sold via shop tab.
    */
    'shopTabSoldItems'?: number;
    /**
    * Number of unique product clicks from Shop Tab.
    */
    'uniqueShopTabProductClicks'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "estimatedShopTabCustomers",
            "baseName": "estimated_shop_tab_customers",
            "type": "number"
        },
        {
            "name": "shopTabCtorSku",
            "baseName": "shop_tab_ctor_sku",
            "type": "string"
        },
        {
            "name": "shopTabCtr",
            "baseName": "shop_tab_ctr",
            "type": "string"
        },
        {
            "name": "shopTabGmv",
            "baseName": "shop_tab_gmv",
            "type": "Analytics202605GetShopProductPerformanceListResponseDataProductsShopTabPerformanceShopTabGmv"
        },
        {
            "name": "shopTabProductClicks",
            "baseName": "shop_tab_product_clicks",
            "type": "number"
        },
        {
            "name": "shopTabProductImpressions",
            "baseName": "shop_tab_product_impressions",
            "type": "number"
        },
        {
            "name": "shopTabSoldItems",
            "baseName": "shop_tab_sold_items",
            "type": "number"
        },
        {
            "name": "uniqueShopTabProductClicks",
            "baseName": "unique_shop_tab_product_clicks",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202605GetShopProductPerformanceListResponseDataProductsShopTabPerformance.attributeTypeMap;
    }
}

