/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202604GetLogisticsTrackingResponseDataLogisticsDetails } from './GetLogisticsTrackingResponseDataLogisticsDetails';

export class Logistics202604GetLogisticsTrackingResponseData {
    /**
    * A list of logistics details. One order may contain multiple parcels.
    */
    'logisticsDetails'?: Array<Logistics202604GetLogisticsTrackingResponseDataLogisticsDetails>;
    /**
    * TikTok Shop order ID.
    */
    'orderId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "logisticsDetails",
            "baseName": "logistics_details",
            "type": "Array<Logistics202604GetLogisticsTrackingResponseDataLogisticsDetails>"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202604GetLogisticsTrackingResponseData.attributeTypeMap;
    }
}

