/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202604GetLogisticsTrackingResponseDataLogisticsDetailsTrackList } from './GetLogisticsTrackingResponseDataLogisticsDetailsTrackList';

export class Logistics202604GetLogisticsTrackingResponseDataLogisticsDetails {
    /**
    * The carrier name.
    */
    'carrierName'?: string;
    /**
    * The latest logistics tracking number for this parcel.
    */
    'newestTrackingNo'?: string;
    /**
    * A list of logistics tracking events for this parcel.
    */
    'trackList'?: Array<Logistics202604GetLogisticsTrackingResponseDataLogisticsDetailsTrackList>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "carrierName",
            "baseName": "carrier_name",
            "type": "string"
        },
        {
            "name": "newestTrackingNo",
            "baseName": "newest_tracking_no",
            "type": "string"
        },
        {
            "name": "trackList",
            "baseName": "track_list",
            "type": "Array<Logistics202604GetLogisticsTrackingResponseDataLogisticsDetailsTrackList>"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202604GetLogisticsTrackingResponseDataLogisticsDetails.attributeTypeMap;
    }
}

