/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Fulfillment202606GetPodDetailResponseDataPodDetails } from './GetPodDetailResponseDataPodDetails';

export class Fulfillment202606GetPodDetailResponseData {
    /**
    * Pod customization order information.
    */
    'podDetails'?: Array<Fulfillment202606GetPodDetailResponseDataPodDetails>;
    /**
    * response status
    */
    'statusCode'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "podDetails",
            "baseName": "pod_details",
            "type": "Array<Fulfillment202606GetPodDetailResponseDataPodDetails>"
        },
        {
            "name": "statusCode",
            "baseName": "status_code",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Fulfillment202606GetPodDetailResponseData.attributeTypeMap;
    }
}

