/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202606GetSPSMetricDiagnosisResponseDataCalculationRule {
    /**
    * Denominator label.
    */
    'denominatorLabel'?: string;
    /**
    * Denominator value.
    */
    'denominatorValue'?: string;
    /**
    * Numerator label.
    */
    'numeratorLabel'?: string;
    /**
    * Numerator value.
    */
    'numeratorValue'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "denominatorLabel",
            "baseName": "denominator_label",
            "type": "string"
        },
        {
            "name": "denominatorValue",
            "baseName": "denominator_value",
            "type": "string"
        },
        {
            "name": "numeratorLabel",
            "baseName": "numerator_label",
            "type": "string"
        },
        {
            "name": "numeratorValue",
            "baseName": "numerator_value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202606GetSPSMetricDiagnosisResponseDataCalculationRule.attributeTypeMap;
    }
}

