/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202606GetSPSMetricDiagnosisResponseDataAnalyses {
    /**
    * Detailed explanations for the selected metric diagnosis.
    */
    'details'?: Array<string>;
    /**
    * Summarized causes affecting the selected metric.
    */
    'summaries'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "details",
            "baseName": "details",
            "type": "Array<string>"
        },
        {
            "name": "summaries",
            "baseName": "summaries",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202606GetSPSMetricDiagnosisResponseDataAnalyses.attributeTypeMap;
    }
}

