/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202606GetSPSMetricProblemDetailsResponseDataOtdrProblemOrderItems {
    /**
    * Actual deliver time. Unix timestamp in seconds.
    */
    'actualDeliverTime'?: number;
    /**
    * Expected deliver time. Unix timestamp in seconds.
    */
    'expectDeliverTime'?: number;
    /**
    * Order ID.
    */
    'orderId'?: string;
    /**
    * Product name.
    */
    'productName'?: string;
    /**
    * SKU ID.
    */
    'skuId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actualDeliverTime",
            "baseName": "actual_deliver_time",
            "type": "number"
        },
        {
            "name": "expectDeliverTime",
            "baseName": "expect_deliver_time",
            "type": "number"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        },
        {
            "name": "productName",
            "baseName": "product_name",
            "type": "string"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202606GetSPSMetricProblemDetailsResponseDataOtdrProblemOrderItems.attributeTypeMap;
    }
}

