/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202606GetSPSMetricProblemDetailsResponseDataSfcrProblemOrderItems {
    /**
    * Cancellation reasons.
    */
    'cancellationReasons'?: Array<string>;
    /**
    * Order creation time. Unix timestamp in seconds.
    */
    'orderCreateTime'?: number;
    /**
    * Order ID.
    */
    'orderId'?: string;
    /**
    * Product ID, when available.
    */
    'productId'?: string;
    /**
    * Product name.
    */
    'productName'?: string;
    /**
    * SKU ID.
    */
    'skuId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cancellationReasons",
            "baseName": "cancellation_reasons",
            "type": "Array<string>"
        },
        {
            "name": "orderCreateTime",
            "baseName": "order_create_time",
            "type": "number"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        },
        {
            "name": "productName",
            "baseName": "product_name",
            "type": "string"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202606GetSPSMetricProblemDetailsResponseDataSfcrProblemOrderItems.attributeTypeMap;
    }
}

