/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202606GetSPSMetricDiagnosisResponseDataDistributionDetails {
    /**
    * Number of items in the distribution bucket.
    */
    'count'?: number;
    /**
    * Distribution detail name. 
    */
    'name'?: string;
    /**
    * Percentage of items in the distribution bucket, from 0 to 100.
    */
    'percent'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "percent",
            "baseName": "percent",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202606GetSPSMetricDiagnosisResponseDataDistributionDetails.attributeTypeMap;
    }
}

