/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202606GetSPSOverviewResponseDataTopIssuesIssues {
    /**
    * Localized issue description.
    */
    'description'?: string;
    /**
    * Issue evaluation period end time. Unix timestamp in seconds.
    */
    'endEvaluationTime'?: number;
    /**
    * Number of days included in this issue\'s evaluation period.
    */
    'evaluateDurationDays'?: number;
    /**
    * Related metric code. Possible values include NRR, NBFR, SFCR, OTDR, AHT, and IM_DSAT.
    */
    'metricCode'?: string;
    /**
    * Localized metric display name.
    */
    'metricName'?: string;
    /**
    * Metric percentile among peer shops, from 0 to 100.
    */
    'percentile'?: string;
    /**
    * Issue rank, where 1 is the top issue.
    */
    'rank'?: number;
    /**
    * Issue evaluation period start time. Unix timestamp in seconds.
    */
    'startEvaluationTime'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "endEvaluationTime",
            "baseName": "end_evaluation_time",
            "type": "number"
        },
        {
            "name": "evaluateDurationDays",
            "baseName": "evaluate_duration_days",
            "type": "number"
        },
        {
            "name": "metricCode",
            "baseName": "metric_code",
            "type": "string"
        },
        {
            "name": "metricName",
            "baseName": "metric_name",
            "type": "string"
        },
        {
            "name": "percentile",
            "baseName": "percentile",
            "type": "string"
        },
        {
            "name": "rank",
            "baseName": "rank",
            "type": "number"
        },
        {
            "name": "startEvaluationTime",
            "baseName": "start_evaluation_time",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202606GetSPSOverviewResponseDataTopIssuesIssues.attributeTypeMap;
    }
}

