/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202606GetSPSMetricsResponseDataMetrics } from './GetSPSMetricsResponseDataMetrics';

export class Analytics202606GetSPSMetricsResponseData {
    /**
    * Fixed complete SPS metric set for the authorized shop.
    */
    'metrics'?: Array<Analytics202606GetSPSMetricsResponseDataMetrics>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "metrics",
            "baseName": "metrics",
            "type": "Array<Analytics202606GetSPSMetricsResponseDataMetrics>"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202606GetSPSMetricsResponseData.attributeTypeMap;
    }
}

