/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202606GetSPSMetricTopItemsResponseDataNbfrTopProductItems {
    /**
    * Product image URL.
    */
    'imageUrl'?: string;
    /**
    * Product ID.
    */
    'productId'?: string;
    /**
    * Product name.
    */
    'productName'?: string;
    /**
    * Number of return or refund orders.
    */
    'returnOrderCount'?: number;
    /**
    * Number of orders associated with the top return or refund reason.
    */
    'topReasonOrderCount'?: number;
    /**
    * Top return or refund reasons.
    */
    'topReturnReasons'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "imageUrl",
            "baseName": "image_url",
            "type": "string"
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        },
        {
            "name": "productName",
            "baseName": "product_name",
            "type": "string"
        },
        {
            "name": "returnOrderCount",
            "baseName": "return_order_count",
            "type": "number"
        },
        {
            "name": "topReasonOrderCount",
            "baseName": "top_reason_order_count",
            "type": "number"
        },
        {
            "name": "topReturnReasons",
            "baseName": "top_return_reasons",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202606GetSPSMetricTopItemsResponseDataNbfrTopProductItems.attributeTypeMap;
    }
}

