/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202606GetSPSMetricDiagnosisResponseDataTrendDataPoints } from './GetSPSMetricDiagnosisResponseDataTrendDataPoints';

export class Analytics202606GetSPSMetricDiagnosisResponseDataTrend {
    /**
    * Metric trend data points.
    */
    'dataPoints'?: Array<Analytics202606GetSPSMetricDiagnosisResponseDataTrendDataPoints>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dataPoints",
            "baseName": "data_points",
            "type": "Array<Analytics202606GetSPSMetricDiagnosisResponseDataTrendDataPoints>"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202606GetSPSMetricDiagnosisResponseDataTrend.attributeTypeMap;
    }
}

