/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202606GetSPSMetricsResponseDataMetricsBenchmarks } from './GetSPSMetricsResponseDataMetricsBenchmarks';

export class Analytics202606GetSPSMetricsResponseDataMetrics {
    'benchmarks'?: Analytics202606GetSPSMetricsResponseDataMetricsBenchmarks;
    /**
    * SPS dimension that the metric belongs to.
    */
    'dimension'?: string;
    /**
    * Metric evaluation period end time. Unix timestamp in seconds.
    */
    'endEvaluationTime'?: number;
    /**
    * Number of days included in this metric\'s evaluation period.
    */
    'evaluateDurationDays'?: number;
    /**
    * Stable metric code. Possible values include NRR, NBFR, SFCR, OTDR, AHT, and IM_DSAT.
    */
    'metricCode'?: string;
    /**
    * Localized metric display name.
    */
    'metricName'?: string;
    /**
    * Metric score, from 0 to 5.
    */
    'score'?: string;
    /**
    * Metric evaluation period start time. Unix timestamp in seconds.
    */
    'startEvaluationTime'?: number;
    /**
    * Metric status. Possible values include EXCELLENT, GOOD, POOR, CRITICAL and NIL.
    */
    'status'?: string;
    /**
    * Metric status text. Values like Excellent, Good, Normal, Attention.
    */
    'statusText'?: string;
    /**
    * Indicates that this metric is a key contributor to SPS.
    */
    'topReasonText'?: string;
    /**
    * Metric value. Hours are represented as values; percentages are represented as values from 0 to 100.
    */
    'value'?: string;
    /**
    * Unit of the metric value. Possible values include PERCENT and HOURS.
    */
    'valueUnit'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "benchmarks",
            "baseName": "benchmarks",
            "type": "Analytics202606GetSPSMetricsResponseDataMetricsBenchmarks"
        },
        {
            "name": "dimension",
            "baseName": "dimension",
            "type": "string"
        },
        {
            "name": "endEvaluationTime",
            "baseName": "end_evaluation_time",
            "type": "number"
        },
        {
            "name": "evaluateDurationDays",
            "baseName": "evaluate_duration_days",
            "type": "number"
        },
        {
            "name": "metricCode",
            "baseName": "metric_code",
            "type": "string"
        },
        {
            "name": "metricName",
            "baseName": "metric_name",
            "type": "string"
        },
        {
            "name": "score",
            "baseName": "score",
            "type": "string"
        },
        {
            "name": "startEvaluationTime",
            "baseName": "start_evaluation_time",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "statusText",
            "baseName": "status_text",
            "type": "string"
        },
        {
            "name": "topReasonText",
            "baseName": "top_reason_text",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "valueUnit",
            "baseName": "value_unit",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202606GetSPSMetricsResponseDataMetrics.attributeTypeMap;
    }
}

