/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202606GetSPSMetricTopItemsResponseDataNrrTopProductItems {
    /**
    * Total number of delivered orders.
    */
    'deliveredOrderCount'?: number;
    /**
    * Product image URL.
    */
    'imageUrl'?: string;
    /**
    * Number of orders with negative reviews.
    */
    'negativeOrderCount'?: number;
    /**
    * Product ID.
    */
    'productId'?: string;
    /**
    * Product name.
    */
    'productName'?: string;
    /**
    * Top negative review reasons.
    */
    'topReviewReasons'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "deliveredOrderCount",
            "baseName": "delivered_order_count",
            "type": "number"
        },
        {
            "name": "imageUrl",
            "baseName": "image_url",
            "type": "string"
        },
        {
            "name": "negativeOrderCount",
            "baseName": "negative_order_count",
            "type": "number"
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        },
        {
            "name": "productName",
            "baseName": "product_name",
            "type": "string"
        },
        {
            "name": "topReviewReasons",
            "baseName": "top_review_reasons",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202606GetSPSMetricTopItemsResponseDataNrrTopProductItems.attributeTypeMap;
    }
}

