/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202606GetSPSOverviewResponseDataBenefits {
    /**
    * Benefit display name localized by the requested locale.
    */
    'benefitName'?: string;
    /**
    * Whether the shop has unlocked this benefit.
    */
    'isUnlocked'?: boolean;
    /**
    * Score required to unlock the benefit, from 0 to 5.
    */
    'unlockScore'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "benefitName",
            "baseName": "benefit_name",
            "type": "string"
        },
        {
            "name": "isUnlocked",
            "baseName": "is_unlocked",
            "type": "boolean"
        },
        {
            "name": "unlockScore",
            "baseName": "unlock_score",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202606GetSPSOverviewResponseDataBenefits.attributeTypeMap;
    }
}

