/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202606GetSPSOverviewResponseDataTopIssuesIssues } from './GetSPSOverviewResponseDataTopIssuesIssues';

export class Analytics202606GetSPSOverviewResponseDataTopIssues {
    /**
    * Ranked issue list.
    */
    'issues'?: Array<Analytics202606GetSPSOverviewResponseDataTopIssuesIssues>;
    /**
    * Localized summary of the top issues.
    */
    'summary'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "issues",
            "baseName": "issues",
            "type": "Array<Analytics202606GetSPSOverviewResponseDataTopIssuesIssues>"
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202606GetSPSOverviewResponseDataTopIssues.attributeTypeMap;
    }
}

