/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202606GetSPSMetricDiagnosisResponseDataTrendDataPoints {
    /**
    * Trend date in yyyyMMdd format.
    */
    'recordDate'?: string;
    /**
    * Metric value on the trend date, using the same unit as value_unit.
    */
    'value'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "recordDate",
            "baseName": "record_date",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202606GetSPSMetricDiagnosisResponseDataTrendDataPoints.attributeTypeMap;
    }
}

