/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202605GetProductSKPPDetailResponseDataTaskDetailsActionSuggestions {
    /**
    * Expected score increase. 预计可提升分数。
    */
    'scoreIncrease'?: number;
    /**
    * Action URL. 操作跳转链接。
    */
    'url'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "scoreIncrease",
            "baseName": "score_increase",
            "type": "number"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202605GetProductSKPPDetailResponseDataTaskDetailsActionSuggestions.attributeTypeMap;
    }
}

