/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202605GetProductSKPPDetailResponseDataRewards } from './GetProductSKPPDetailResponseDataRewards';
import { Product202605GetProductSKPPDetailResponseDataTaskDetails } from './GetProductSKPPDetailResponseDataTaskDetails';

export class Product202605GetProductSKPPDetailResponseData {
    /**
    * Affiliate Program enrolment. Enum: ACTIVE / INACTIVE. Affiliate 计划状态。
    */
    'affiliateProgramStatus'?: string;
    /**
    * Platform product ID. 平台商品唯一 ID。
    */
    'productId'?: string;
    /**
    * Available SKPP rewards for the product. 商品可用的 SKPP 奖励列表。
    */
    'rewards'?: Array<Product202605GetProductSKPPDetailResponseDataRewards>;
    /**
    * Enum: QUALIFIED / NOT_QUALIFIED / NOT_ELIGIBLE 当前 SKPP 状态。
    */
    'skppStatus'?: string;
    /**
    * Score required to pass SKPP. SKPP 达标目标分。
    */
    'targetScore'?: number;
    /**
    * Per-category SKPP tasks and scoring details. 各类 SKPP 任务与得分详情。
    */
    'taskDetails'?: Array<Product202605GetProductSKPPDetailResponseDataTaskDetails>;
    /**
    * Current total SKPP score. 当前 SKPP 总分。
    */
    'totalScore'?: number;
    /**
    * Offline data date as Unix timestamp (seconds). Refresh cadence: T+1 (occasionally T+2). 离线数据日期，更新节奏 T+1（偶发 T+2）。
    */
    'updateTime'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "affiliateProgramStatus",
            "baseName": "affiliate_program_status",
            "type": "string"
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        },
        {
            "name": "rewards",
            "baseName": "rewards",
            "type": "Array<Product202605GetProductSKPPDetailResponseDataRewards>"
        },
        {
            "name": "skppStatus",
            "baseName": "skpp_status",
            "type": "string"
        },
        {
            "name": "targetScore",
            "baseName": "target_score",
            "type": "number"
        },
        {
            "name": "taskDetails",
            "baseName": "task_details",
            "type": "Array<Product202605GetProductSKPPDetailResponseDataTaskDetails>"
        },
        {
            "name": "totalScore",
            "baseName": "total_score",
            "type": "number"
        },
        {
            "name": "updateTime",
            "baseName": "update_time",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Product202605GetProductSKPPDetailResponseData.attributeTypeMap;
    }
}

