/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202605GetShopSKPPSummaryResponseDataShopSummary } from './GetShopSKPPSummaryResponseDataShopSummary';

export class Product202605GetShopSKPPSummaryResponseData {
    'shopSummary'?: Product202605GetShopSKPPSummaryResponseDataShopSummary;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "shopSummary",
            "baseName": "shop_summary",
            "type": "Product202605GetShopSKPPSummaryResponseDataShopSummary"
        }    ];

    static getAttributeTypeMap() {
        return Product202605GetShopSKPPSummaryResponseData.attributeTypeMap;
    }
}

