/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */
import { Analytics202309GetLiveRoomCoreStatsResponse } from '../model/analytics/V202309/GetLiveRoomCoreStatsResponse';
import { Analytics202309GetLiveRoomGMVTrendResponse } from '../model/analytics/V202309/GetLiveRoomGMVTrendResponse';
import { Analytics202309GetLiveRoomInteractiveTrendsResponse } from '../model/analytics/V202309/GetLiveRoomInteractiveTrendsResponse';
import { Analytics202309GetLiveRoomProductStatsResponse } from '../model/analytics/V202309/GetLiveRoomProductStatsResponse';
import { Analytics202309GetLiveRoomTrafficPerformanceResponse } from '../model/analytics/V202309/GetLiveRoomTrafficPerformanceResponse';
import { Analytics202309GetLiveRoomUserPortraitsResponse } from '../model/analytics/V202309/GetLiveRoomUserPortraitsResponse';
import { Analytics202309GetLiveRoomViewTrendsResponse } from '../model/analytics/V202309/GetLiveRoomViewTrendsResponse';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://open-api.tiktokglobalshop.com';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum AnalyticsV202309ApiApiKeys {
}

export class AnalyticsV202309Api {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    static readonly apiName = 'AnalyticsV202309Api' as const;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: AnalyticsV202309ApiApiKeys, value: string) {
        (this.authentications as any)[AnalyticsV202309ApiApiKeys[key]].apiKey = value;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * This API returns the core stats of live detail, e.g. GMV.
     * @summary GetLiveRoomCoreStats
     * @param liveRoomId the live stream room id
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     */
    public async LiveRoomsLiveRoomIdCoreStatsGet (liveRoomId: string, xTtsAccessToken: string, contentType: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: Analytics202309GetLiveRoomCoreStatsResponse;  }> {
        const localVarPath = this.basePath + '/analytics/202309/live_rooms/{live_room_id}/core_stats'
            .replace('{' + 'live_room_id' + '}', encodeURIComponent(String(liveRoomId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'liveRoomId' is not null or undefined
        if (liveRoomId === null || liveRoomId === undefined) {
            throw new Error('Required parameter liveRoomId was null or undefined when calling LiveRoomsLiveRoomIdCoreStatsGet.');
        }

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling LiveRoomsLiveRoomIdCoreStatsGet.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling LiveRoomsLiveRoomIdCoreStatsGet.');
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: Analytics202309GetLiveRoomCoreStatsResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "Analytics202309GetLiveRoomCoreStatsResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * This API gets the trend points of gmv related information
     * @summary GetLiveRoomGMVTrend
     * @param liveRoomId live stream room id
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     */
    public async LiveRoomsLiveRoomIdGmvTrendPerformancesGet (liveRoomId: string, xTtsAccessToken: string, contentType: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: Analytics202309GetLiveRoomGMVTrendResponse;  }> {
        const localVarPath = this.basePath + '/analytics/202309/live_rooms/{live_room_id}/gmv_trend_performances'
            .replace('{' + 'live_room_id' + '}', encodeURIComponent(String(liveRoomId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'liveRoomId' is not null or undefined
        if (liveRoomId === null || liveRoomId === undefined) {
            throw new Error('Required parameter liveRoomId was null or undefined when calling LiveRoomsLiveRoomIdGmvTrendPerformancesGet.');
        }

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling LiveRoomsLiveRoomIdGmvTrendPerformancesGet.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling LiveRoomsLiveRoomIdGmvTrendPerformancesGet.');
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: Analytics202309GetLiveRoomGMVTrendResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "Analytics202309GetLiveRoomGMVTrendResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * This API gets interactive performance trend data.
     * @summary GetLiveRoomInteractiveTrends
     * @param liveRoomId live stream room id
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     */
    public async LiveRoomsLiveRoomIdInteractiveTrendPerformancesGet (liveRoomId: string, xTtsAccessToken: string, contentType: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: Analytics202309GetLiveRoomInteractiveTrendsResponse;  }> {
        const localVarPath = this.basePath + '/analytics/202309/live_rooms/{live_room_id}/interactive_trend_performances'
            .replace('{' + 'live_room_id' + '}', encodeURIComponent(String(liveRoomId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'liveRoomId' is not null or undefined
        if (liveRoomId === null || liveRoomId === undefined) {
            throw new Error('Required parameter liveRoomId was null or undefined when calling LiveRoomsLiveRoomIdInteractiveTrendPerformancesGet.');
        }

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling LiveRoomsLiveRoomIdInteractiveTrendPerformancesGet.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling LiveRoomsLiveRoomIdInteractiveTrendPerformancesGet.');
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: Analytics202309GetLiveRoomInteractiveTrendsResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "Analytics202309GetLiveRoomInteractiveTrendsResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * This API gets the product list of live room
     * @summary GetLiveRoomProductStats
     * @param liveRoomId live stream room id
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     */
    public async LiveRoomsLiveRoomIdProductStatsGet (liveRoomId: string, xTtsAccessToken: string, contentType: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: Analytics202309GetLiveRoomProductStatsResponse;  }> {
        const localVarPath = this.basePath + '/analytics/202309/live_rooms/{live_room_id}/product_stats'
            .replace('{' + 'live_room_id' + '}', encodeURIComponent(String(liveRoomId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'liveRoomId' is not null or undefined
        if (liveRoomId === null || liveRoomId === undefined) {
            throw new Error('Required parameter liveRoomId was null or undefined when calling LiveRoomsLiveRoomIdProductStatsGet.');
        }

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling LiveRoomsLiveRoomIdProductStatsGet.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling LiveRoomsLiveRoomIdProductStatsGet.');
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: Analytics202309GetLiveRoomProductStatsResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "Analytics202309GetLiveRoomProductStatsResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * This API gets the  traffic performances of live streaming for distribution analysis
     * @summary GetLiveRoomTrafficPerformance
     * @param liveRoomId live stream room id
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     */
    public async LiveRoomsLiveRoomIdTrafficPerformancesGet (liveRoomId: string, xTtsAccessToken: string, contentType: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: Analytics202309GetLiveRoomTrafficPerformanceResponse;  }> {
        const localVarPath = this.basePath + '/analytics/202309/live_rooms/{live_room_id}/traffic_performances'
            .replace('{' + 'live_room_id' + '}', encodeURIComponent(String(liveRoomId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'liveRoomId' is not null or undefined
        if (liveRoomId === null || liveRoomId === undefined) {
            throw new Error('Required parameter liveRoomId was null or undefined when calling LiveRoomsLiveRoomIdTrafficPerformancesGet.');
        }

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling LiveRoomsLiveRoomIdTrafficPerformancesGet.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling LiveRoomsLiveRoomIdTrafficPerformancesGet.');
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: Analytics202309GetLiveRoomTrafficPerformanceResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "Analytics202309GetLiveRoomTrafficPerformanceResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * This API gets the user portrait of live room
     * @summary GetLiveRoomUserPortraits
     * @param liveRoomId live stream room id
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     */
    public async LiveRoomsLiveRoomIdUserPortraitsGet (liveRoomId: string, xTtsAccessToken: string, contentType: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: Analytics202309GetLiveRoomUserPortraitsResponse;  }> {
        const localVarPath = this.basePath + '/analytics/202309/live_rooms/{live_room_id}/user_portraits'
            .replace('{' + 'live_room_id' + '}', encodeURIComponent(String(liveRoomId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'liveRoomId' is not null or undefined
        if (liveRoomId === null || liveRoomId === undefined) {
            throw new Error('Required parameter liveRoomId was null or undefined when calling LiveRoomsLiveRoomIdUserPortraitsGet.');
        }

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling LiveRoomsLiveRoomIdUserPortraitsGet.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling LiveRoomsLiveRoomIdUserPortraitsGet.');
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: Analytics202309GetLiveRoomUserPortraitsResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "Analytics202309GetLiveRoomUserPortraitsResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Use this API to retrieve the viewer counts and trends of a live room
     * @summary GetLiveRoomViewTrends
     * @param liveRoomId live stream room id
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     */
    public async LiveRoomsLiveRoomIdViewTrendPerformancesGet (liveRoomId: string, xTtsAccessToken: string, contentType: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: Analytics202309GetLiveRoomViewTrendsResponse;  }> {
        const localVarPath = this.basePath + '/analytics/202309/live_rooms/{live_room_id}/view_trend_performances'
            .replace('{' + 'live_room_id' + '}', encodeURIComponent(String(liveRoomId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'liveRoomId' is not null or undefined
        if (liveRoomId === null || liveRoomId === undefined) {
            throw new Error('Required parameter liveRoomId was null or undefined when calling LiveRoomsLiveRoomIdViewTrendPerformancesGet.');
        }

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling LiveRoomsLiveRoomIdViewTrendPerformancesGet.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling LiveRoomsLiveRoomIdViewTrendPerformancesGet.');
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: Analytics202309GetLiveRoomViewTrendsResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "Analytics202309GetLiveRoomViewTrendsResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
}

export const AnalyticsV202309ApiOperationNames = {
    LiveRoomsLiveRoomIdCoreStatsGet: 'LiveRoomsLiveRoomIdCoreStatsGet',LiveRoomsLiveRoomIdGmvTrendPerformancesGet: 'LiveRoomsLiveRoomIdGmvTrendPerformancesGet',LiveRoomsLiveRoomIdInteractiveTrendPerformancesGet: 'LiveRoomsLiveRoomIdInteractiveTrendPerformancesGet',LiveRoomsLiveRoomIdProductStatsGet: 'LiveRoomsLiveRoomIdProductStatsGet',LiveRoomsLiveRoomIdTrafficPerformancesGet: 'LiveRoomsLiveRoomIdTrafficPerformancesGet',LiveRoomsLiveRoomIdUserPortraitsGet: 'LiveRoomsLiveRoomIdUserPortraitsGet',LiveRoomsLiveRoomIdViewTrendPerformancesGet: 'LiveRoomsLiveRoomIdViewTrendPerformancesGet',
} as const


export type AnalyticsV202309ApiOperationTypes = {
    LiveRoomsLiveRoomIdCoreStatsGet: AnalyticsV202309Api['LiveRoomsLiveRoomIdCoreStatsGet'];LiveRoomsLiveRoomIdGmvTrendPerformancesGet: AnalyticsV202309Api['LiveRoomsLiveRoomIdGmvTrendPerformancesGet'];LiveRoomsLiveRoomIdInteractiveTrendPerformancesGet: AnalyticsV202309Api['LiveRoomsLiveRoomIdInteractiveTrendPerformancesGet'];LiveRoomsLiveRoomIdProductStatsGet: AnalyticsV202309Api['LiveRoomsLiveRoomIdProductStatsGet'];LiveRoomsLiveRoomIdTrafficPerformancesGet: AnalyticsV202309Api['LiveRoomsLiveRoomIdTrafficPerformancesGet'];LiveRoomsLiveRoomIdUserPortraitsGet: AnalyticsV202309Api['LiveRoomsLiveRoomIdUserPortraitsGet'];LiveRoomsLiveRoomIdViewTrendPerformancesGet: AnalyticsV202309Api['LiveRoomsLiveRoomIdViewTrendPerformancesGet'];
};

