/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */
import { Analytics202502GetLiveRoomCoreStatsResponse } from '../model/analytics/V202502/GetLiveRoomCoreStatsResponse';
import { Analytics202502GetLiveRoomGMVTrendResponse } from '../model/analytics/V202502/GetLiveRoomGMVTrendResponse';
import { Analytics202502GetLiveRoomInteractiveTrendsResponse } from '../model/analytics/V202502/GetLiveRoomInteractiveTrendsResponse';
import { Analytics202502GetLiveRoomProductStatsResponse } from '../model/analytics/V202502/GetLiveRoomProductStatsResponse';
import { Analytics202502GetLiveRoomTrafficPerformanceResponse } from '../model/analytics/V202502/GetLiveRoomTrafficPerformanceResponse';
import { Analytics202502GetLiveRoomUserPortraitsResponse } from '../model/analytics/V202502/GetLiveRoomUserPortraitsResponse';
import { Analytics202502GetLiveRoomViewTrendsResponse } from '../model/analytics/V202502/GetLiveRoomViewTrendsResponse';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://open-api.tiktokglobalshop.com';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum AnalyticsV202502ApiApiKeys {
}

export class AnalyticsV202502Api {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    static readonly apiName = 'AnalyticsV202502Api' as const;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: AnalyticsV202502ApiApiKeys, value: string) {
        (this.authentications as any)[AnalyticsV202502ApiApiKeys[key]].apiKey = value;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * Returns core stats for the specified live room, including GMV, order counts, buyer counts, product click counts, and view counts.
     * @summary GetLiveRoomCoreStats
     * @param liveRoomId the live stream room id
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     */
    public async LiveRoomsLiveRoomIdCoreStatsGet (liveRoomId: string, xTtsAccessToken: string, contentType: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: Analytics202502GetLiveRoomCoreStatsResponse;  }> {
        const localVarPath = this.basePath + '/analytics/202502/live_rooms/{live_room_id}/core_stats'
            .replace('{' + 'live_room_id' + '}', encodeURIComponent(String(liveRoomId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'liveRoomId' is not null or undefined
        if (liveRoomId === null || liveRoomId === undefined) {
            throw new Error('Required parameter liveRoomId was null or undefined when calling LiveRoomsLiveRoomIdCoreStatsGet.');
        }

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling LiveRoomsLiveRoomIdCoreStatsGet.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling LiveRoomsLiveRoomIdCoreStatsGet.');
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: Analytics202502GetLiveRoomCoreStatsResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "Analytics202502GetLiveRoomCoreStatsResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Returns GMV trend performance points for the specified live room, including GMV and created-order trend values.
     * @summary GetLiveRoomGMVTrend
     * @param liveRoomId live stream room id
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     */
    public async LiveRoomsLiveRoomIdGmvTrendPerformancesGet (liveRoomId: string, xTtsAccessToken: string, contentType: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: Analytics202502GetLiveRoomGMVTrendResponse;  }> {
        const localVarPath = this.basePath + '/analytics/202502/live_rooms/{live_room_id}/gmv_trend_performances'
            .replace('{' + 'live_room_id' + '}', encodeURIComponent(String(liveRoomId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'liveRoomId' is not null or undefined
        if (liveRoomId === null || liveRoomId === undefined) {
            throw new Error('Required parameter liveRoomId was null or undefined when calling LiveRoomsLiveRoomIdGmvTrendPerformancesGet.');
        }

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling LiveRoomsLiveRoomIdGmvTrendPerformancesGet.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling LiveRoomsLiveRoomIdGmvTrendPerformancesGet.');
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: Analytics202502GetLiveRoomGMVTrendResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "Analytics202502GetLiveRoomGMVTrendResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Returns interactive trend performance points for the specified live room, including watch, comment, and share counts.
     * @summary GetLiveRoomInteractiveTrends
     * @param liveRoomId live stream room id
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     */
    public async LiveRoomsLiveRoomIdInteractiveTrendPerformancesGet (liveRoomId: string, xTtsAccessToken: string, contentType: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: Analytics202502GetLiveRoomInteractiveTrendsResponse;  }> {
        const localVarPath = this.basePath + '/analytics/202502/live_rooms/{live_room_id}/interactive_trend_performances'
            .replace('{' + 'live_room_id' + '}', encodeURIComponent(String(liveRoomId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'liveRoomId' is not null or undefined
        if (liveRoomId === null || liveRoomId === undefined) {
            throw new Error('Required parameter liveRoomId was null or undefined when calling LiveRoomsLiveRoomIdInteractiveTrendPerformancesGet.');
        }

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling LiveRoomsLiveRoomIdInteractiveTrendPerformancesGet.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling LiveRoomsLiveRoomIdInteractiveTrendPerformancesGet.');
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: Analytics202502GetLiveRoomInteractiveTrendsResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "Analytics202502GetLiveRoomInteractiveTrendsResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Returns the product list for the specified live room, including product IDs, names, GMV, unit price, inventory counts, and click counts.
     * @summary GetLiveRoomProductStats
     * @param liveRoomId live stream room id
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     */
    public async LiveRoomsLiveRoomIdProductStatsGet (liveRoomId: string, xTtsAccessToken: string, contentType: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: Analytics202502GetLiveRoomProductStatsResponse;  }> {
        const localVarPath = this.basePath + '/analytics/202502/live_rooms/{live_room_id}/product_stats'
            .replace('{' + 'live_room_id' + '}', encodeURIComponent(String(liveRoomId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'liveRoomId' is not null or undefined
        if (liveRoomId === null || liveRoomId === undefined) {
            throw new Error('Required parameter liveRoomId was null or undefined when calling LiveRoomsLiveRoomIdProductStatsGet.');
        }

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling LiveRoomsLiveRoomIdProductStatsGet.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling LiveRoomsLiveRoomIdProductStatsGet.');
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: Analytics202502GetLiveRoomProductStatsResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "Analytics202502GetLiveRoomProductStatsResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Returns traffic performance for the specified live room, including source and sub-source watch counts for distribution analysis.
     * @summary GetLiveRoomTrafficPerformance
     * @param liveRoomId live stream room id
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     */
    public async LiveRoomsLiveRoomIdTrafficPerformancesGet (liveRoomId: string, xTtsAccessToken: string, contentType: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: Analytics202502GetLiveRoomTrafficPerformanceResponse;  }> {
        const localVarPath = this.basePath + '/analytics/202502/live_rooms/{live_room_id}/traffic_performances'
            .replace('{' + 'live_room_id' + '}', encodeURIComponent(String(liveRoomId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'liveRoomId' is not null or undefined
        if (liveRoomId === null || liveRoomId === undefined) {
            throw new Error('Required parameter liveRoomId was null or undefined when calling LiveRoomsLiveRoomIdTrafficPerformancesGet.');
        }

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling LiveRoomsLiveRoomIdTrafficPerformancesGet.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling LiveRoomsLiveRoomIdTrafficPerformancesGet.');
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: Analytics202502GetLiveRoomTrafficPerformanceResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "Analytics202502GetLiveRoomTrafficPerformanceResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Returns user portrait indicators for the specified live room, including age, gender, fan, advertisement, and region distributions.
     * @summary GetLiveRoomUserPortraits
     * @param liveRoomId The ID of the live stream room whose user portrait indicators are requested.
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     */
    public async LiveRoomsLiveRoomIdUserPortraitsGet (liveRoomId: string, xTtsAccessToken: string, contentType: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: Analytics202502GetLiveRoomUserPortraitsResponse;  }> {
        const localVarPath = this.basePath + '/analytics/202502/live_rooms/{live_room_id}/user_portraits'
            .replace('{' + 'live_room_id' + '}', encodeURIComponent(String(liveRoomId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'liveRoomId' is not null or undefined
        if (liveRoomId === null || liveRoomId === undefined) {
            throw new Error('Required parameter liveRoomId was null or undefined when calling LiveRoomsLiveRoomIdUserPortraitsGet.');
        }

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling LiveRoomsLiveRoomIdUserPortraitsGet.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling LiveRoomsLiveRoomIdUserPortraitsGet.');
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: Analytics202502GetLiveRoomUserPortraitsResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "Analytics202502GetLiveRoomUserPortraitsResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Returns viewer count trend data points for the specified live room, grouped by online, entering, and leaving viewers.
     * @summary GetLiveRoomViewTrends
     * @param liveRoomId The ID of the live stream room whose viewer trend data is requested.
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     */
    public async LiveRoomsLiveRoomIdViewTrendPerformancesGet (liveRoomId: string, xTtsAccessToken: string, contentType: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: Analytics202502GetLiveRoomViewTrendsResponse;  }> {
        const localVarPath = this.basePath + '/analytics/202502/live_rooms/{live_room_id}/view_trend_performances'
            .replace('{' + 'live_room_id' + '}', encodeURIComponent(String(liveRoomId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'liveRoomId' is not null or undefined
        if (liveRoomId === null || liveRoomId === undefined) {
            throw new Error('Required parameter liveRoomId was null or undefined when calling LiveRoomsLiveRoomIdViewTrendPerformancesGet.');
        }

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling LiveRoomsLiveRoomIdViewTrendPerformancesGet.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling LiveRoomsLiveRoomIdViewTrendPerformancesGet.');
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: Analytics202502GetLiveRoomViewTrendsResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "Analytics202502GetLiveRoomViewTrendsResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
}

export const AnalyticsV202502ApiOperationNames = {
    LiveRoomsLiveRoomIdCoreStatsGet: 'LiveRoomsLiveRoomIdCoreStatsGet',LiveRoomsLiveRoomIdGmvTrendPerformancesGet: 'LiveRoomsLiveRoomIdGmvTrendPerformancesGet',LiveRoomsLiveRoomIdInteractiveTrendPerformancesGet: 'LiveRoomsLiveRoomIdInteractiveTrendPerformancesGet',LiveRoomsLiveRoomIdProductStatsGet: 'LiveRoomsLiveRoomIdProductStatsGet',LiveRoomsLiveRoomIdTrafficPerformancesGet: 'LiveRoomsLiveRoomIdTrafficPerformancesGet',LiveRoomsLiveRoomIdUserPortraitsGet: 'LiveRoomsLiveRoomIdUserPortraitsGet',LiveRoomsLiveRoomIdViewTrendPerformancesGet: 'LiveRoomsLiveRoomIdViewTrendPerformancesGet',
} as const


export type AnalyticsV202502ApiOperationTypes = {
    LiveRoomsLiveRoomIdCoreStatsGet: AnalyticsV202502Api['LiveRoomsLiveRoomIdCoreStatsGet'];LiveRoomsLiveRoomIdGmvTrendPerformancesGet: AnalyticsV202502Api['LiveRoomsLiveRoomIdGmvTrendPerformancesGet'];LiveRoomsLiveRoomIdInteractiveTrendPerformancesGet: AnalyticsV202502Api['LiveRoomsLiveRoomIdInteractiveTrendPerformancesGet'];LiveRoomsLiveRoomIdProductStatsGet: AnalyticsV202502Api['LiveRoomsLiveRoomIdProductStatsGet'];LiveRoomsLiveRoomIdTrafficPerformancesGet: AnalyticsV202502Api['LiveRoomsLiveRoomIdTrafficPerformancesGet'];LiveRoomsLiveRoomIdUserPortraitsGet: AnalyticsV202502Api['LiveRoomsLiveRoomIdUserPortraitsGet'];LiveRoomsLiveRoomIdViewTrendPerformancesGet: AnalyticsV202502Api['LiveRoomsLiveRoomIdViewTrendPerformancesGet'];
};

