/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */
import { ReturnRefund202606GetReviewDecisionResponse } from '../model/returnRefund/V202606/GetReviewDecisionResponse';
import { ReturnRefund202606RejectReturnRequestBody } from '../model/returnRefund/V202606/RejectReturnRequestBody';
import { ReturnRefund202606RejectReturnResponse } from '../model/returnRefund/V202606/RejectReturnResponse';
import { ReturnRefund202606ReviewAftersalesRequestBody } from '../model/returnRefund/V202606/ReviewAftersalesRequestBody';
import { ReturnRefund202606ReviewAftersalesResponse } from '../model/returnRefund/V202606/ReviewAftersalesResponse';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://open-api.tiktokglobalshop.com';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum ReturnRefundV202606ApiApiKeys {
}

export class ReturnRefundV202606Api {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    static readonly apiName = 'ReturnRefundV202606Api' as const;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: ReturnRefundV202606ApiApiKeys, value: string) {
        (this.authentications as any)[ReturnRefundV202606ApiApiKeys[key]].apiKey = value;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * API used to review (approve, reject, or offer alternatives to) a buyer\'s return request.
     * @summary ReviewAftersales
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     * @param shopCipher 
     * @param ReviewAftersalesRequestBody 
     */
    public async AftersalesReviewPost (xTtsAccessToken: string, contentType: string, shopCipher?: string, ReviewAftersalesRequestBody?: ReturnRefund202606ReviewAftersalesRequestBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: ReturnRefund202606ReviewAftersalesResponse;  }> {
        const localVarPath = this.basePath + '/return_refund/202606/aftersales/review';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling AftersalesReviewPost.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling AftersalesReviewPost.');
        }

        if (shopCipher !== undefined) {
            localVarQueryParameters['shop_cipher'] = ObjectSerializer.serialize(shopCipher, "string");
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(ReviewAftersalesRequestBody, "ReturnRefund202606ReviewAftersalesRequestBody")
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: ReturnRefund202606ReviewAftersalesResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "ReturnRefund202606ReviewAftersalesResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Use this API to reject a buyer\'s return or refund request. The valid decision depends on the current request type and status. Before calling this API, make sure the request is still awaiting the seller action that matches the decision you send.
     * @summary RejectReturn
     * @param returnId The unique identifier of the return request to be rejected by the seller.
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     * @param idempotencyKey The idempotency key is a unique value generated by the client which the server uses to recognize the same request. How you create unique keys is up to you, but we suggest using UUIDs, or another random string with enough entropy to avoid collisions. Idempotency keys can be up to 255 characters long.
     * @param shopCipher 
     * @param RejectReturnRequestBody 
     */
    public async ReturnsReturnIdRejectPost (returnId: string, xTtsAccessToken: string, contentType: string, idempotencyKey?: string, shopCipher?: string, RejectReturnRequestBody?: ReturnRefund202606RejectReturnRequestBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: ReturnRefund202606RejectReturnResponse;  }> {
        const localVarPath = this.basePath + '/return_refund/202606/returns/{return_id}/reject'
            .replace('{' + 'return_id' + '}', encodeURIComponent(String(returnId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'returnId' is not null or undefined
        if (returnId === null || returnId === undefined) {
            throw new Error('Required parameter returnId was null or undefined when calling ReturnsReturnIdRejectPost.');
        }

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling ReturnsReturnIdRejectPost.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling ReturnsReturnIdRejectPost.');
        }

        if (idempotencyKey !== undefined) {
            localVarQueryParameters['idempotency_key'] = ObjectSerializer.serialize(idempotencyKey, "string");
        }

        if (shopCipher !== undefined) {
            localVarQueryParameters['shop_cipher'] = ObjectSerializer.serialize(shopCipher, "string");
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(RejectReturnRequestBody, "ReturnRefund202606RejectReturnRequestBody")
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: ReturnRefund202606RejectReturnResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "ReturnRefund202606RejectReturnResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Description of [GET]/return_refund/:version/Get_Review_Decision
     * @summary GetReviewDecision
     * @param sellerId The unique identifier of the seller/shop 
     * @param returnOrCancelId The TikTok Shop return or cancellation request ID to evaluate. Pass the request identifier for the target cancellation, refund, return, or other supported aftersales flow. Do not pass an order ID or order line ID in this field.
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     * @param locale The BCP-47 locale codes for displaying the return reason, delimited by commas. Default: en-US Refer to [Locale codes](678e3a47bae28f030a8c7523) for the list of supported locale codes.
     * @param checkDecisions The seller decisions to evaluate for the specified aftersales request. Possible Values: - &#x60;APPROVE_REQUEST_CANCEL&#x60; - &#x60;APPROVE_REFUND&#x60; - &#x60;APPROVE_RETURN&#x60; - &#x60;APPROVE_RECEIVED_PACKAGE&#x60; - &#x60;APPROVE_REPLACEMENT&#x60; - &#x60;ISSUE_REPLACEMENT_REFUND&#x60; - &#x60;DIRECT_REFUND&#x60; - &#x60;REJECT_REQUEST_CANCEL&#x60; - &#x60;REJECT_REFUND&#x60; - &#x60;REJECT_RETURN&#x60; - &#x60;REJECT_RECEIVED_PACKAGE&#x60; - &#x60;REJECT_REPLACEMENT&#x60; -&#x60;ISSUE_EXCHANGE_REFUND&#x60; -&#x60;OFFER_PARTIAL_REFUND_AFTER_RECEIVING_PKG&#x60; **Note:** When omitted, the API evaluates all supported seller decisions for the request and returns one result per decision.
     * @param shopCipher 
     */
    public async ReviewDecisionGet (sellerId: number, returnOrCancelId: string, xTtsAccessToken: string, contentType: string, locale?: string, checkDecisions?: Array<string>, shopCipher?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: ReturnRefund202606GetReviewDecisionResponse;  }> {
        const localVarPath = this.basePath + '/return_refund/202606/review_decision';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'sellerId' is not null or undefined
        if (sellerId === null || sellerId === undefined) {
            throw new Error('Required parameter sellerId was null or undefined when calling ReviewDecisionGet.');
        }

        // verify required parameter 'returnOrCancelId' is not null or undefined
        if (returnOrCancelId === null || returnOrCancelId === undefined) {
            throw new Error('Required parameter returnOrCancelId was null or undefined when calling ReviewDecisionGet.');
        }

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling ReviewDecisionGet.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling ReviewDecisionGet.');
        }

        if (sellerId !== undefined) {
            localVarQueryParameters['seller_id'] = ObjectSerializer.serialize(sellerId, "number");
        }

        if (returnOrCancelId !== undefined) {
            localVarQueryParameters['return_or_cancel_id'] = ObjectSerializer.serialize(returnOrCancelId, "string");
        }

        if (locale !== undefined) {
            localVarQueryParameters['locale'] = ObjectSerializer.serialize(locale, "string");
        }

        if (checkDecisions !== undefined) {
            localVarQueryParameters['check_decisions'] = ObjectSerializer.serialize(checkDecisions, "Array<string>");
        }

        if (shopCipher !== undefined) {
            localVarQueryParameters['shop_cipher'] = ObjectSerializer.serialize(shopCipher, "string");
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: ReturnRefund202606GetReviewDecisionResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "ReturnRefund202606GetReviewDecisionResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
}

export const ReturnRefundV202606ApiOperationNames = {
    AftersalesReviewPost: 'AftersalesReviewPost',ReturnsReturnIdRejectPost: 'ReturnsReturnIdRejectPost',ReviewDecisionGet: 'ReviewDecisionGet',
} as const


export type ReturnRefundV202606ApiOperationTypes = {
    AftersalesReviewPost: ReturnRefundV202606Api['AftersalesReviewPost'];ReturnsReturnIdRejectPost: ReturnRefundV202606Api['ReturnsReturnIdRejectPost'];ReviewDecisionGet: ReturnRefundV202606Api['ReviewDecisionGet'];
};

