/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202605CancelTargetCollaborationConflictsResponseDataFailedItems {
    /**
    * Creator Open ID. [More details](https://partner.tiktokshop.com/docv2/page/3obfokj6)
    */
    'creatorOpenId'?: string;
    /**
    * The confict target collaboration id
    */
    'existingCollaborationId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "creatorOpenId",
            "baseName": "creator_open_id",
            "type": "string"
        },
        {
            "name": "existingCollaborationId",
            "baseName": "existing_collaboration_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202605CancelTargetCollaborationConflictsResponseDataFailedItems.attributeTypeMap;
    }
}

