/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202605CancelTargetCollaborationConflictsResponseDataFailedItems } from './CancelTargetCollaborationConflictsResponseDataFailedItems';
import { AffiliateSeller202605CancelTargetCollaborationConflictsResponseDataSuccessItems } from './CancelTargetCollaborationConflictsResponseDataSuccessItems';

export class AffiliateSeller202605CancelTargetCollaborationConflictsResponseData {
    /**
    * failed update items
    */
    'failedItems'?: Array<AffiliateSeller202605CancelTargetCollaborationConflictsResponseDataFailedItems>;
    /**
    * success update items
    */
    'successItems'?: Array<AffiliateSeller202605CancelTargetCollaborationConflictsResponseDataSuccessItems>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "failedItems",
            "baseName": "failed_items",
            "type": "Array<AffiliateSeller202605CancelTargetCollaborationConflictsResponseDataFailedItems>"
        },
        {
            "name": "successItems",
            "baseName": "success_items",
            "type": "Array<AffiliateSeller202605CancelTargetCollaborationConflictsResponseDataSuccessItems>"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202605CancelTargetCollaborationConflictsResponseData.attributeTypeMap;
    }
}

