/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202605CheckTargetCollaborationConflictsRequestBody {
    /**
    * Creator Open ID List. [More details](https://partner.tiktokshop.com/docv2/page/3obfokj6)
    */
    'creatorOpenIdList'?: Array<string>;
    /**
    * product id list
    */
    'productIdList'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "creatorOpenIdList",
            "baseName": "creator_open_id_list",
            "type": "Array<string>"
        },
        {
            "name": "productIdList",
            "baseName": "product_id_list",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202605CheckTargetCollaborationConflictsRequestBody.attributeTypeMap;
    }
}

