/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202605CheckTargetCollaborationConflictsResponseDataConflictItems } from './CheckTargetCollaborationConflictsResponseDataConflictItems';

export class AffiliateSeller202605CheckTargetCollaborationConflictsResponseData {
    /**
    * A list of user and product identifiers with target collaboration conflicts that caused target collaboration failure.
    */
    'conflictItems'?: Array<AffiliateSeller202605CheckTargetCollaborationConflictsResponseDataConflictItems>;
    /**
    * Indicates whether a conflict exists between the creator and the product. (Returns `true` if a conflict is detected.)
    */
    'hasConflict'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "conflictItems",
            "baseName": "conflict_items",
            "type": "Array<AffiliateSeller202605CheckTargetCollaborationConflictsResponseDataConflictItems>"
        },
        {
            "name": "hasConflict",
            "baseName": "has_conflict",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202605CheckTargetCollaborationConflictsResponseData.attributeTypeMap;
    }
}

