/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Order202606PodDetailsResponseDataPodDetails {
    /**
    * The pod customization Json string.
    */
    'orderLineId'?: string;
    /**
    * The unique identifier of the order line item.
    */
    'podDetail'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderLineId",
            "baseName": "order_line_id",
            "type": "string"
        },
        {
            "name": "podDetail",
            "baseName": "pod_detail",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Order202606PodDetailsResponseDataPodDetails.attributeTypeMap;
    }
}

