/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202406GetShopSKUPerformanceDetailResponseDataPerformanceComparisonIntervals } from './GetShopSKUPerformanceDetailResponseDataPerformanceComparisonIntervals';
import { Analytics202406GetShopSKUPerformanceDetailResponseDataPerformanceIntervals } from './GetShopSKUPerformanceDetailResponseDataPerformanceIntervals';

export class Analytics202406GetShopSKUPerformanceDetailResponseDataPerformance {
    /**
    * Same structure as \"intervals\" It contains data for the previous time range with the same range length and granularity as the current time range Example, if current time range (represented in start_time_ge and end_time_lt) is from 2024-04-01 to 2024-04-08) with granularity \"ALL\", the previous_intervals will contain data from 2024-03-25 to 2024-04-01 with granularity \"ALL\"
    */
    'comparisonIntervals'?: Array<Analytics202406GetShopSKUPerformanceDetailResponseDataPerformanceComparisonIntervals>;
    /**
    * Interval data for the requested time range. The time range of each interval is determined by the granularity.
    */
    'intervals'?: Array<Analytics202406GetShopSKUPerformanceDetailResponseDataPerformanceIntervals>;
    /**
    * The unique identifier of the product that contains the SKU.
    */
    'productId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "comparisonIntervals",
            "baseName": "comparison_intervals",
            "type": "Array<Analytics202406GetShopSKUPerformanceDetailResponseDataPerformanceComparisonIntervals>"
        },
        {
            "name": "intervals",
            "baseName": "intervals",
            "type": "Array<Analytics202406GetShopSKUPerformanceDetailResponseDataPerformanceIntervals>"
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202406GetShopSKUPerformanceDetailResponseDataPerformance.attributeTypeMap;
    }
}

