/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateCreator202504CreatorGeneratePublisherLinkRequestBodyMaterial {
    /**
    * The list of material IDs. The max length is 50.
    */
    'ids'?: Array<string>;
    /**
    * When `type` is set to `CAMPAIGN`, this field is required. This schema is associated with the Campaign page.
    */
    'promotionCampaignSchema'?: string;
    /**
    * Right now, the only possible value is `PRODUCT` or `CAMPAIGN`. When `material_ids==PRODUCT`, use pids for material IDs.
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ids",
            "baseName": "ids",
            "type": "Array<string>"
        },
        {
            "name": "promotionCampaignSchema",
            "baseName": "promotion_campaign_schema",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202504CreatorGeneratePublisherLinkRequestBodyMaterial.attributeTypeMap;
    }
}

