/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202309GetLiveRoomCoreStatsResponseDataStats } from './GetLiveRoomCoreStatsResponseDataStats';

export class Analytics202309GetLiveRoomCoreStatsResponseData {
    'stats'?: Analytics202309GetLiveRoomCoreStatsResponseDataStats;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "stats",
            "baseName": "stats",
            "type": "Analytics202309GetLiveRoomCoreStatsResponseDataStats"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202309GetLiveRoomCoreStatsResponseData.attributeTypeMap;
    }
}

