/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202309GetLiveRoomTrafficPerformanceResponseDataTrafficPerformancesSource {
    /**
    * The name of the live source
    */
    'name'?: string;
    /**
    * Watch page value, e.g. Watch count
    */
    'watchPv'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "watchPv",
            "baseName": "watch_pv",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202309GetLiveRoomTrafficPerformanceResponseDataTrafficPerformancesSource.attributeTypeMap;
    }
}

