/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202309GetLiveRoomViewTrendsResponseDataViewTrendPerformancesDataPoints } from './GetLiveRoomViewTrendsResponseDataViewTrendPerformancesDataPoints';

export class Analytics202309GetLiveRoomViewTrendsResponseDataViewTrendPerformances {
    /**
    * The data point of view trend
    */
    'dataPoints'?: Array<Analytics202309GetLiveRoomViewTrendsResponseDataViewTrendPerformancesDataPoints>;
    /**
    * The stats_type describes the type of value below.  TREND_ONLINE_VIEWER:the viewers who are watching the live streaming room  TREND_ENTER_VIEWER: the viewers who enter  the live streaming room  TREND_LEFT_VIEWER: the viewers who left the live streaming room
    */
    'statsType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dataPoints",
            "baseName": "data_points",
            "type": "Array<Analytics202309GetLiveRoomViewTrendsResponseDataViewTrendPerformancesDataPoints>"
        },
        {
            "name": "statsType",
            "baseName": "stats_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202309GetLiveRoomViewTrendsResponseDataViewTrendPerformances.attributeTypeMap;
    }
}

