/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202309GetLiveRoomTrafficPerformanceResponseDataTrafficPerformancesSource } from './GetLiveRoomTrafficPerformanceResponseDataTrafficPerformancesSource';
import { Analytics202309GetLiveRoomTrafficPerformanceResponseDataTrafficPerformancesSubSources } from './GetLiveRoomTrafficPerformanceResponseDataTrafficPerformancesSubSources';

export class Analytics202309GetLiveRoomTrafficPerformanceResponseDataTrafficPerformances {
    'source'?: Analytics202309GetLiveRoomTrafficPerformanceResponseDataTrafficPerformancesSource;
    /**
    * The sub source of the source 
    */
    'subSources'?: Array<Analytics202309GetLiveRoomTrafficPerformanceResponseDataTrafficPerformancesSubSources>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "source",
            "baseName": "source",
            "type": "Analytics202309GetLiveRoomTrafficPerformanceResponseDataTrafficPerformancesSource"
        },
        {
            "name": "subSources",
            "baseName": "sub_sources",
            "type": "Array<Analytics202309GetLiveRoomTrafficPerformanceResponseDataTrafficPerformancesSubSources>"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202309GetLiveRoomTrafficPerformanceResponseDataTrafficPerformances.attributeTypeMap;
    }
}

