/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202509PartialEditProductRequestBodyPodInfoPodTemplatesSurfaces } from './PartialEditProductRequestBodyPodInfoPodTemplatesSurfaces';

export class Product202509PartialEditProductRequestBodyPodInfoPodTemplates {
    /**
    * The unique identifier of the POD customization template. This field is generated by the system and is not required when creating a new template.
    */
    'podTemplateId'?: string;
    /**
    * Optional notes or instructions for this customization template. These notes may be used to remind consumers about customization requirements on the customization page.
    */
    'remark'?: string;
    /**
    * A list of product SKU IDs associated with this customization template. The same SKU cannot be associated with more than one template.
    */
    'skuIds'?: Array<string>;
    /**
    * A list of customizable product surfaces under this template, such as the front side, back side, collar, or sleeve. A template can contain up to 10 surfaces.
    */
    'surfaces'?: Array<Product202509PartialEditProductRequestBodyPodInfoPodTemplatesSurfaces>;
    /**
    * The name of the customization template, used by the seller for internal management.
    */
    'templateName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "podTemplateId",
            "baseName": "pod_template_id",
            "type": "string"
        },
        {
            "name": "remark",
            "baseName": "remark",
            "type": "string"
        },
        {
            "name": "skuIds",
            "baseName": "sku_ids",
            "type": "Array<string>"
        },
        {
            "name": "surfaces",
            "baseName": "surfaces",
            "type": "Array<Product202509PartialEditProductRequestBodyPodInfoPodTemplatesSurfaces>"
        },
        {
            "name": "templateName",
            "baseName": "template_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202509PartialEditProductRequestBodyPodInfoPodTemplates.attributeTypeMap;
    }
}

