/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202509PartialEditProductRequestBodyPodInfoPodTemplatesSurfacesCustomAreasAreaPlacement {
    /**
    * The height of the customizable area. Supports two decimal places.
    */
    'height'?: string;
    /**
    * The rotation angle of the customizable area, in degrees. Supports two decimal places.
    */
    'rotateDegree'?: string;
    /**
    * The width of the customizable area. Supports two decimal places.
    */
    'width'?: string;
    /**
    * The X-coordinate of the customizable area\'s starting point on the surface. Supports two decimal places.
    */
    'xCoordinate'?: string;
    /**
    * The Y-coordinate of the customizable area\'s starting point on the surface. Supports two decimal places.
    */
    'yCoordinate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "height",
            "baseName": "height",
            "type": "string"
        },
        {
            "name": "rotateDegree",
            "baseName": "rotate_degree",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "string"
        },
        {
            "name": "xCoordinate",
            "baseName": "x_coordinate",
            "type": "string"
        },
        {
            "name": "yCoordinate",
            "baseName": "y_coordinate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202509PartialEditProductRequestBodyPodInfoPodTemplatesSurfacesCustomAreasAreaPlacement.attributeTypeMap;
    }
}

