/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202509PartialEditProductRequestBodyPodInfoPodTemplatesSurfacesCustomAreasImageAreaDefaultImage } from './PartialEditProductRequestBodyPodInfoPodTemplatesSurfacesCustomAreasImageAreaDefaultImage';

export class Product202509PartialEditProductRequestBodyPodInfoPodTemplatesSurfacesCustomAreasImageArea {
    'defaultImage'?: Product202509PartialEditProductRequestBodyPodInfoPodTemplatesSurfacesCustomAreasImageAreaDefaultImage;
    /**
    * The minimum required height, in pixels, for an image uploaded by the consumer.
    */
    'minHeight'?: number;
    /**
    * The minimum required width, in pixels, for an image uploaded by the consumer.
    */
    'minWidth'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "defaultImage",
            "baseName": "default_image",
            "type": "Product202509PartialEditProductRequestBodyPodInfoPodTemplatesSurfacesCustomAreasImageAreaDefaultImage"
        },
        {
            "name": "minHeight",
            "baseName": "min_height",
            "type": "number"
        },
        {
            "name": "minWidth",
            "baseName": "min_width",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Product202509PartialEditProductRequestBodyPodInfoPodTemplatesSurfacesCustomAreasImageArea.attributeTypeMap;
    }
}

