/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202509PartialEditProductRequestBodyReplicatedProductsSkus } from './PartialEditProductRequestBodyReplicatedProductsSkus';

export class Product202509PartialEditProductRequestBodyReplicatedProducts {
    /**
    * Defines the inventory mode for the duplicated target product. This parameter supports two modes: SHARED and EXCLUSIVE.   - SHARED: In this mode, the inventory of all interconnected (shared) products must be strictly consistent; otherwise, an error will be returned. - EXCLUSIVE: In this mode, the inventory for each product can be set independently without affecting others.   Applicability: This feature is applicable ONLY for the EU market.   Default Value: If left empty, the system defaults to the EXCLUSIVE mode.
    */
    'inventoryMode'?: string;
    /**
    * The market where you want to publish the global product.Possible values: - AT: Austria - BE:Belgium - CZ:Czech Republic - DE: Germany - ES: Spain - FR: France - GB: United Kingdom - GR: Greece - HU:Hungary - ID: Indonesia - IE: Ireland - IT: Italy - JP: Japan - MY: Malaysia - NL: Netherlands(NL) - PH: Philippines - PO: Poland - PT:Portugal - SG: Singapore - TH: Thailand - US: United States - VN: Vietnam - MX: Mexico
    */
    'region'?: string;
    /**
    * The SKUs to be synced to the specified market. Specify this **only if** you are adding SKUs or changing the sales attribute id/name. **Note**: - You must pass in all existing SKUs. Any existing SKU IDs not listed here will result in the deletion of those SKUs. For example, if this product contains 5 SKUs and you only provide 2 SKU IDs, the remaining 3 will be deleted. - To create new SKUs, leave the SKU ID blank and provide the seller_sku.
    */
    'skus'?: Array<Product202509PartialEditProductRequestBodyReplicatedProductsSkus>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "inventoryMode",
            "baseName": "inventory_mode",
            "type": "string"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "skus",
            "baseName": "skus",
            "type": "Array<Product202509PartialEditProductRequestBodyReplicatedProductsSkus>"
        }    ];

    static getAttributeTypeMap() {
        return Product202509PartialEditProductRequestBodyReplicatedProducts.attributeTypeMap;
    }
}

