/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202509PartialEditProductRequestBodyPodInfoPodTemplates } from './PartialEditProductRequestBodyPodInfoPodTemplates';

export class Product202509PartialEditProductRequestBodyPodInfo {
    /**
    * A list of POD customization templates. Each template represents one customization plan and can be associated with one or more SKUs.
    */
    'podTemplates'?: Array<Product202509PartialEditProductRequestBodyPodInfoPodTemplates>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "podTemplates",
            "baseName": "pod_templates",
            "type": "Array<Product202509PartialEditProductRequestBodyPodInfoPodTemplates>"
        }    ];

    static getAttributeTypeMap() {
        return Product202509PartialEditProductRequestBodyPodInfo.attributeTypeMap;
    }
}

