/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class ReturnRefund202606RejectReturnRequestBodyPartialRefundAmount {
    /**
    * Country Currency
    */
    'currency'?: string;
    /**
    * Partial Refund Amount
    */
    'partialRefundTotal'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "partialRefundTotal",
            "baseName": "partial_refund_total",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202606RejectReturnRequestBodyPartialRefundAmount.attributeTypeMap;
    }
}

