/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202606ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsAlternativeSolutionDetails } from './ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsAlternativeSolutionDetails';
import { ReturnRefund202606ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsLineItems } from './ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsLineItems';
import { ReturnRefund202606ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsReason } from './ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsReason';

export class ReturnRefund202606ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisions {
    /**
    * Action/decision to be applied. Possible values: - `APPROVE_REQUEST` - `APPROVE_RETURN_PACKAGE` - `REJECT_REQUEST` - `REJECT_RETURN_PACKAGE` - `REFUND_INSTEAD` - `OFFER_PARTIAL_REFUND` - `OFFER_PARTIAL_REFUND_AFTER_RECEIVING_PKG`
    */
    'action'?: string;
    'alternativeSolutionDetails'?: ReturnRefund202606ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsAlternativeSolutionDetails;
    /**
    * Line items for which this decision applies. Decision details apply to each line item individually (e.g. a partial refund amount of $1.00 for 3 line items will result in a total partial refund amount of $3.00).
    */
    'lineItems'?: Array<ReturnRefund202606ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsLineItems>;
    'reason'?: ReturnRefund202606ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsReason;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "string"
        },
        {
            "name": "alternativeSolutionDetails",
            "baseName": "alternative_solution_details",
            "type": "ReturnRefund202606ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsAlternativeSolutionDetails"
        },
        {
            "name": "lineItems",
            "baseName": "line_items",
            "type": "Array<ReturnRefund202606ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsLineItems>"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "ReturnRefund202606ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsReason"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202606ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisions.attributeTypeMap;
    }
}

