/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202309EditGlobalProductResponseDataPublishResultsFailReasons } from './EditGlobalProductResponseDataPublishResultsFailReasons';

export class Product202309EditGlobalProductResponseDataPublishResults {
    /**
    * The list of errors that occurred.
    */
    'failReasons'?: Array<Product202309EditGlobalProductResponseDataPublishResultsFailReasons>;
    /**
    * The market where you want to publish the global product.Possible values: - AT: Austria - BE:Belgium - CZ:Czech Republic - DE: Germany - ES: Spain - FR: France - GB: United Kingdom - GR: Greece - HU:Hungary - ID: Indonesia - IE: Ireland - IT: Italy - JP: Japan - MY: Malaysia - NL: Netherlands(NL) - PH: Philippines - PO: Poland - PT:Portugal - SG: Singapore - TH: Thailand - US: United States - VN: Vietnam - MX: Mexico
    */
    'region'?: string;
    /**
    * The status of syncing the product to the market. Possible values: - SUCCESS: The global product was successfully synchronized to the local shop, submitted for listing, and is now under review. - FAILED: Synchronization of the global product to the local shop was unsuccessful.
    */
    'status'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "failReasons",
            "baseName": "fail_reasons",
            "type": "Array<Product202309EditGlobalProductResponseDataPublishResultsFailReasons>"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202309EditGlobalProductResponseDataPublishResults.attributeTypeMap;
    }
}

