/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesBackgroundImage } from './GetProductResponseDataPodInfoPodTemplatesSurfacesBackgroundImage';
import { Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreas } from './GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreas';
import { Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesMaskImage } from './GetProductResponseDataPodInfoPodTemplatesSurfacesMaskImage';

export class Product202309GetProductResponseDataPodInfoPodTemplatesSurfaces {
    'backgroundImage'?: Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesBackgroundImage;
    /**
    * A list of customizable areas on this surface. The order of the elements represents the layer order to be used when rendering the final customization preview. A surface can contain up to 10 customization areas.
    */
    'customAreas'?: Array<Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreas>;
    /**
    * The seller-defined external identifier of the customizable surface, used for mapping with the seller\'s own system.
    */
    'externalSurfaceId'?: string;
    'maskImage'?: Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesMaskImage;
    /**
    * The name of the customizable surface, for example, `Front Side` or `Back Side`.
    */
    'surfaceName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "backgroundImage",
            "baseName": "background_image",
            "type": "Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesBackgroundImage"
        },
        {
            "name": "customAreas",
            "baseName": "custom_areas",
            "type": "Array<Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreas>"
        },
        {
            "name": "externalSurfaceId",
            "baseName": "external_surface_id",
            "type": "string"
        },
        {
            "name": "maskImage",
            "baseName": "mask_image",
            "type": "Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesMaskImage"
        },
        {
            "name": "surfaceName",
            "baseName": "surface_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202309GetProductResponseDataPodInfoPodTemplatesSurfaces.attributeTypeMap;
    }
}

