/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreasAreaPlacement } from './GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreasAreaPlacement';
import { Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreasImageArea } from './GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreasImageArea';
import { Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreasTextArea } from './GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreasTextArea';

export class Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreas {
    /**
    * The name of the customizable area.
    */
    'areaName'?: string;
    'areaPlacement'?: Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreasAreaPlacement;
    /**
    * The type of the customizable area. Enum values: `TEXT`, `IMAGE`.
    */
    'areaType'?: string;
    /**
    * The seller-defined external identifier of the customizable area, used for mapping with the seller\'s own system.
    */
    'externalAreaId'?: string;
    'imageArea'?: Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreasImageArea;
    /**
    * Specifies whether the consumer must provide customization content for this area. If set to `false`, the default content or base product version may be used.
    */
    'isRequired'?: boolean;
    'textArea'?: Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreasTextArea;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "areaName",
            "baseName": "area_name",
            "type": "string"
        },
        {
            "name": "areaPlacement",
            "baseName": "area_placement",
            "type": "Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreasAreaPlacement"
        },
        {
            "name": "areaType",
            "baseName": "area_type",
            "type": "string"
        },
        {
            "name": "externalAreaId",
            "baseName": "external_area_id",
            "type": "string"
        },
        {
            "name": "imageArea",
            "baseName": "image_area",
            "type": "Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreasImageArea"
        },
        {
            "name": "isRequired",
            "baseName": "is_required",
            "type": "boolean"
        },
        {
            "name": "textArea",
            "baseName": "text_area",
            "type": "Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreasTextArea"
        }    ];

    static getAttributeTypeMap() {
        return Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreas.attributeTypeMap;
    }
}

