/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreasTextArea {
    /**
    * The text alignment type. Enum values: `LEFT`, `CENTER`, `RIGHT`.
    */
    'alignType'?: string;
    /**
    * A list of text colors available for consumers to choose from, using hexadecimal color values such as `#FFFFFF`.
    */
    'colors'?: Array<string>;
    /**
    * Optional default text displayed in this area. If the consumer does not customize this area, the default text may be used.
    */
    'defaultText'?: string;
    /**
    * A list of font keys available for consumers to choose from, based on the platform-supported font library.
    */
    'fonts'?: Array<string>;
    /**
    * The maximum number of characters allowed for consumer text input.
    */
    'maxTextLength'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "alignType",
            "baseName": "align_type",
            "type": "string"
        },
        {
            "name": "colors",
            "baseName": "colors",
            "type": "Array<string>"
        },
        {
            "name": "defaultText",
            "baseName": "default_text",
            "type": "string"
        },
        {
            "name": "fonts",
            "baseName": "fonts",
            "type": "Array<string>"
        },
        {
            "name": "maxTextLength",
            "baseName": "max_text_length",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Product202309GetProductResponseDataPodInfoPodTemplatesSurfacesCustomAreasTextArea.attributeTypeMap;
    }
}

