/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202309PartialEditProductRequestBodyReplicatedProductsSkusPrice {
    /**
    * The currency. Possible values based on the region: - BRL: Brazil - CZK: Czech Republic - EUR: France, Germany, Ireland, Italy, Spain, Netherlands, Belgium, Austria, Greece, Portugal - GBP: United Kingdom - HUF: Hungary - IDR: Indonesia - JPY: Japan - MXN: Mexico - MYR: Malaysia - PHP: Philippines - PLN: Poland - SGD: Singapore - THB: Thailand - USD: United States - VND: Vietnam
    */
    'currency'?: string;
    /**
    * The SKU\'s local display price shown on the product page before any discounts.  Refer to Product Pricing for the allowed price ranges in each market.
    */
    'salePrice'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "salePrice",
            "baseName": "sale_price",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202309PartialEditProductRequestBodyReplicatedProductsSkusPrice.attributeTypeMap;
    }
}

