/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202309RecommendCategoryRequestBodyOriginPlatformCategory {
    /**
    * The full category path or full category name on the source platform.
    */
    'fullName'?: string;
    /**
    * The category ID on the source platform.
    */
    'id'?: string;
    /**
    * Whether the category is a leaf category.
    */
    'isLeaf'?: boolean;
    /**
    * Whether the category is a root category.
    */
    'isRoot'?: boolean;
    /**
    * The category name on the source platform.
    */
    'name'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fullName",
            "baseName": "full_name",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "isLeaf",
            "baseName": "is_leaf",
            "type": "boolean"
        },
        {
            "name": "isRoot",
            "baseName": "is_root",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202309RecommendCategoryRequestBodyOriginPlatformCategory.attributeTypeMap;
    }
}

