/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202309RecommendCategoryRequestBodyOriginPlatformProductMetaDataAttributeValueList } from './RecommendCategoryRequestBodyOriginPlatformProductMetaDataAttributeValueList';

export class Product202309RecommendCategoryRequestBodyOriginPlatformProductMetaData {
    /**
    * A list of product metadata attributes and their values.
    */
    'attributeValueList'?: Array<Product202309RecommendCategoryRequestBodyOriginPlatformProductMetaDataAttributeValueList>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "attributeValueList",
            "baseName": "attribute_value_list",
            "type": "Array<Product202309RecommendCategoryRequestBodyOriginPlatformProductMetaDataAttributeValueList>"
        }    ];

    static getAttributeTypeMap() {
        return Product202309RecommendCategoryRequestBodyOriginPlatformProductMetaData.attributeTypeMap;
    }
}

