/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202309RecommendCategoryRequestBodyOriginPlatformProductMetaDataAttributeValueList {
    /**
    * The metadata attribute name.
    */
    'name'?: string;
    /**
    * The values associated with the metadata attribute.
    */
    'values'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Product202309RecommendCategoryRequestBodyOriginPlatformProductMetaDataAttributeValueList.attributeTypeMap;
    }
}

