/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Promotion202309CreatePromotionActivityRequestBodyDiscountBmsmDiscount } from './CreatePromotionActivityRequestBodyDiscountBmsmDiscount';
import { Promotion202309CreatePromotionActivityRequestBodyDiscountBxgyDiscount } from './CreatePromotionActivityRequestBodyDiscountBxgyDiscount';
import { Promotion202309CreatePromotionActivityRequestBodyDiscountGiftDiscount } from './CreatePromotionActivityRequestBodyDiscountGiftDiscount';
import { Promotion202309CreatePromotionActivityRequestBodyDiscountShippingDiscount } from './CreatePromotionActivityRequestBodyDiscountShippingDiscount';

export class Promotion202309CreatePromotionActivityRequestBodyDiscount {
    'bmsmDiscount'?: Promotion202309CreatePromotionActivityRequestBodyDiscountBmsmDiscount;
    'bxgyDiscount'?: Promotion202309CreatePromotionActivityRequestBodyDiscountBxgyDiscount;
    'giftDiscount'?: Promotion202309CreatePromotionActivityRequestBodyDiscountGiftDiscount;
    'shippingDiscount'?: Promotion202309CreatePromotionActivityRequestBodyDiscountShippingDiscount;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bmsmDiscount",
            "baseName": "bmsm_discount",
            "type": "Promotion202309CreatePromotionActivityRequestBodyDiscountBmsmDiscount"
        },
        {
            "name": "bxgyDiscount",
            "baseName": "bxgy_discount",
            "type": "Promotion202309CreatePromotionActivityRequestBodyDiscountBxgyDiscount"
        },
        {
            "name": "giftDiscount",
            "baseName": "gift_discount",
            "type": "Promotion202309CreatePromotionActivityRequestBodyDiscountGiftDiscount"
        },
        {
            "name": "shippingDiscount",
            "baseName": "shipping_discount",
            "type": "Promotion202309CreatePromotionActivityRequestBodyDiscountShippingDiscount"
        }    ];

    static getAttributeTypeMap() {
        return Promotion202309CreatePromotionActivityRequestBodyDiscount.attributeTypeMap;
    }
}

