/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Promotion202309SearchPromotionActivitiesResponseDataActivitiesDiscountBmsmDiscount } from './SearchPromotionActivitiesResponseDataActivitiesDiscountBmsmDiscount';
import { Promotion202309SearchPromotionActivitiesResponseDataActivitiesDiscountBxgyDiscount } from './SearchPromotionActivitiesResponseDataActivitiesDiscountBxgyDiscount';
import { Promotion202309SearchPromotionActivitiesResponseDataActivitiesDiscountGiftDiscount } from './SearchPromotionActivitiesResponseDataActivitiesDiscountGiftDiscount';
import { Promotion202309SearchPromotionActivitiesResponseDataActivitiesDiscountShippingDiscount } from './SearchPromotionActivitiesResponseDataActivitiesDiscountShippingDiscount';

export class Promotion202309SearchPromotionActivitiesResponseDataActivitiesDiscount {
    'bmsmDiscount'?: Promotion202309SearchPromotionActivitiesResponseDataActivitiesDiscountBmsmDiscount;
    'bxgyDiscount'?: Promotion202309SearchPromotionActivitiesResponseDataActivitiesDiscountBxgyDiscount;
    'giftDiscount'?: Promotion202309SearchPromotionActivitiesResponseDataActivitiesDiscountGiftDiscount;
    'shippingDiscount'?: Promotion202309SearchPromotionActivitiesResponseDataActivitiesDiscountShippingDiscount;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bmsmDiscount",
            "baseName": "bmsm_discount",
            "type": "Promotion202309SearchPromotionActivitiesResponseDataActivitiesDiscountBmsmDiscount"
        },
        {
            "name": "bxgyDiscount",
            "baseName": "bxgy_discount",
            "type": "Promotion202309SearchPromotionActivitiesResponseDataActivitiesDiscountBxgyDiscount"
        },
        {
            "name": "giftDiscount",
            "baseName": "gift_discount",
            "type": "Promotion202309SearchPromotionActivitiesResponseDataActivitiesDiscountGiftDiscount"
        },
        {
            "name": "shippingDiscount",
            "baseName": "shipping_discount",
            "type": "Promotion202309SearchPromotionActivitiesResponseDataActivitiesDiscountShippingDiscount"
        }    ];

    static getAttributeTypeMap() {
        return Promotion202309SearchPromotionActivitiesResponseDataActivitiesDiscount.attributeTypeMap;
    }
}

