/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Promotion202309UpdatePromotionActivityRequestBodyDiscountBmsmDiscount } from './UpdatePromotionActivityRequestBodyDiscountBmsmDiscount';
import { Promotion202309UpdatePromotionActivityRequestBodyDiscountBxgyDiscount } from './UpdatePromotionActivityRequestBodyDiscountBxgyDiscount';
import { Promotion202309UpdatePromotionActivityRequestBodyDiscountGiftDiscount } from './UpdatePromotionActivityRequestBodyDiscountGiftDiscount';
import { Promotion202309UpdatePromotionActivityRequestBodyDiscountShippingDiscount } from './UpdatePromotionActivityRequestBodyDiscountShippingDiscount';

export class Promotion202309UpdatePromotionActivityRequestBodyDiscount {
    'bmsmDiscount'?: Promotion202309UpdatePromotionActivityRequestBodyDiscountBmsmDiscount;
    'bxgyDiscount'?: Promotion202309UpdatePromotionActivityRequestBodyDiscountBxgyDiscount;
    'giftDiscount'?: Promotion202309UpdatePromotionActivityRequestBodyDiscountGiftDiscount;
    'shippingDiscount'?: Promotion202309UpdatePromotionActivityRequestBodyDiscountShippingDiscount;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bmsmDiscount",
            "baseName": "bmsm_discount",
            "type": "Promotion202309UpdatePromotionActivityRequestBodyDiscountBmsmDiscount"
        },
        {
            "name": "bxgyDiscount",
            "baseName": "bxgy_discount",
            "type": "Promotion202309UpdatePromotionActivityRequestBodyDiscountBxgyDiscount"
        },
        {
            "name": "giftDiscount",
            "baseName": "gift_discount",
            "type": "Promotion202309UpdatePromotionActivityRequestBodyDiscountGiftDiscount"
        },
        {
            "name": "shippingDiscount",
            "baseName": "shipping_discount",
            "type": "Promotion202309UpdatePromotionActivityRequestBodyDiscountShippingDiscount"
        }    ];

    static getAttributeTypeMap() {
        return Promotion202309UpdatePromotionActivityRequestBodyDiscount.attributeTypeMap;
    }
}

