/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Order202605UpdateTheBlindBoxOpeningResultsRequestBodyBlindBatchBoxResultsBlindBoxOrderLineList } from './UpdateTheBlindBoxOpeningResultsRequestBodyBlindBatchBoxResultsBlindBoxOrderLineList';

export class Order202605UpdateTheBlindBoxOpeningResultsRequestBodyBlindBatchBoxResults {
    /**
    * Unboxing results for line items under orders. on batch box version
    */
    'blindBoxOrderLineList'?: Array<Order202605UpdateTheBlindBoxOpeningResultsRequestBodyBlindBatchBoxResultsBlindBoxOrderLineList>;
    /**
    * Line item id in TikTok Shop.
    */
    'orderLineId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blindBoxOrderLineList",
            "baseName": "blind_box_order_line_list",
            "type": "Array<Order202605UpdateTheBlindBoxOpeningResultsRequestBodyBlindBatchBoxResultsBlindBoxOrderLineList>"
        },
        {
            "name": "orderLineId",
            "baseName": "order_line_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Order202605UpdateTheBlindBoxOpeningResultsRequestBodyBlindBatchBoxResults.attributeTypeMap;
    }
}

