/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202509GetShopPerformanceResponseDataPerformanceIntervalsSalesGmvBreakdownsGmv } from './GetShopPerformanceResponseDataPerformanceIntervalsSalesGmvBreakdownsGmv';

export class Analytics202509GetShopPerformanceResponseDataPerformanceIntervalsSalesGmvBreakdowns {
    'gmv'?: Analytics202509GetShopPerformanceResponseDataPerformanceIntervalsSalesGmvBreakdownsGmv;
    /**
    * GMV breakdown type. Possible values: - VIDEO: Video content. - LIVE: Live stream content. - PRODUCT_CARD: Product card.
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "gmv",
            "baseName": "gmv",
            "type": "Analytics202509GetShopPerformanceResponseDataPerformanceIntervalsSalesGmvBreakdownsGmv"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202509GetShopPerformanceResponseDataPerformanceIntervalsSalesGmvBreakdowns.attributeTypeMap;
    }
}

