/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202509GetShopSKUPerformanceDetailResponseDataPerformanceIntervals } from './GetShopSKUPerformanceDetailResponseDataPerformanceIntervals';

export class Analytics202509GetShopSKUPerformanceDetailResponseDataPerformance {
    /**
    * Interval data for the requested time range. The time range of each interval is determined by the granularity.
    */
    'intervals'?: Array<Analytics202509GetShopSKUPerformanceDetailResponseDataPerformanceIntervals>;
    /**
    * The ID of the product that the SKU belongs to.
    */
    'productId'?: number;
    /**
    * The ID of the SKU for this performance object.
    */
    'skuId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "intervals",
            "baseName": "intervals",
            "type": "Array<Analytics202509GetShopSKUPerformanceDetailResponseDataPerformanceIntervals>"
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "number"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202509GetShopSKUPerformanceDetailResponseDataPerformance.attributeTypeMap;
    }
}

