/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202509GetShopSKUPerformanceDetailResponseDataPerformanceIntervalsGmv } from './GetShopSKUPerformanceDetailResponseDataPerformanceIntervalsGmv';
import { Analytics202509GetShopSKUPerformanceDetailResponseDataPerformanceIntervalsGmvBreakdown } from './GetShopSKUPerformanceDetailResponseDataPerformanceIntervalsGmvBreakdown';
import { Analytics202509GetShopSKUPerformanceDetailResponseDataPerformanceIntervalsItemsSoldBreakdown } from './GetShopSKUPerformanceDetailResponseDataPerformanceIntervalsItemsSoldBreakdown';

export class Analytics202509GetShopSKUPerformanceDetailResponseDataPerformanceIntervals {
    /**
    * End date of the interval (ISO 8601 YYYY-MM-DD format) in shop registered timezone, exclusive.
    */
    'endDate'?: string;
    'gmv'?: Analytics202509GetShopSKUPerformanceDetailResponseDataPerformanceIntervalsGmv;
    /**
    * GMV breakdowns for the SKU.
    */
    'gmvBreakdown'?: Array<Analytics202509GetShopSKUPerformanceDetailResponseDataPerformanceIntervalsGmvBreakdown>;
    /**
    * Number of units sold for the SKU.
    */
    'itemsSold'?: number;
    /**
    * Unit sold breakdowns.
    */
    'itemsSoldBreakdown'?: Array<Analytics202509GetShopSKUPerformanceDetailResponseDataPerformanceIntervalsItemsSoldBreakdown>;
    /**
    * Total (sum of all) orders for the SKU.
    */
    'skuOrders'?: number;
    /**
    * Start date of the interval (ISO 8601 YYYY-MM-DD format) in shop registered timezone, inclusive.
    */
    'startDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "endDate",
            "baseName": "end_date",
            "type": "string"
        },
        {
            "name": "gmv",
            "baseName": "gmv",
            "type": "Analytics202509GetShopSKUPerformanceDetailResponseDataPerformanceIntervalsGmv"
        },
        {
            "name": "gmvBreakdown",
            "baseName": "gmv_breakdown",
            "type": "Array<Analytics202509GetShopSKUPerformanceDetailResponseDataPerformanceIntervalsGmvBreakdown>"
        },
        {
            "name": "itemsSold",
            "baseName": "items_sold",
            "type": "number"
        },
        {
            "name": "itemsSoldBreakdown",
            "baseName": "items_sold_breakdown",
            "type": "Array<Analytics202509GetShopSKUPerformanceDetailResponseDataPerformanceIntervalsItemsSoldBreakdown>"
        },
        {
            "name": "skuOrders",
            "baseName": "sku_orders",
            "type": "number"
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202509GetShopSKUPerformanceDetailResponseDataPerformanceIntervals.attributeTypeMap;
    }
}

