/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202509GetShopPerformanceResponseDataPerformanceIntervalsSalesGrossRevenueBreakdowns {
    /**
    * The percentage of revenue generated from the corresponding breakdown type.
    */
    'percentage'?: string;
    /**
    * Gross revenue breakdown type by market. For SEA, MX, and BR markets, possible values are NON_GMV_MAX and GMV_MAX. For UK and EU markets, possible values are ADS and ORGANIC. This breakdown is not applicable for US and JP markets.
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "percentage",
            "baseName": "percentage",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202509GetShopPerformanceResponseDataPerformanceIntervalsSalesGrossRevenueBreakdowns.attributeTypeMap;
    }
}

