/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202509GetShopSKUPerformanceDetailResponseDataPerformanceIntervalsGmvBreakdown {
    /**
    * GMV amount for the corresponding type and currency.
    */
    'amount'?: string;
    /**
    * GMV currency code (ISO 4217 standard). If LOCAL currency is requested, the value will be the local currency code of where the shop is registered (e.g. GBP).
    */
    'currency'?: string;
    /**
    * GMV breakdown type. Possible values: - LIVE: Live stream content. - VIDEO: Video content. - PRODUCT_CARD: Product card.
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202509GetShopSKUPerformanceDetailResponseDataPerformanceIntervalsGmvBreakdown.attributeTypeMap;
    }
}

