/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202607GetWeeklyCreatorOutreachQuotaResponseDataDataGmvLevelRule } from './GetWeeklyCreatorOutreachQuotaResponseDataDataGmvLevelRule';

export class AffiliateSeller202607GetWeeklyCreatorOutreachQuotaResponseDataData {
    /**
    * Quota period end time
    */
    'endTime'?: string;
    /**
    * Quota GMV level rules
    */
    'gmvLevelRule'?: Array<AffiliateSeller202607GetWeeklyCreatorOutreachQuotaResponseDataDataGmvLevelRule>;
    /**
    * Shop gmv tier
    */
    'gmvTier'?: string;
    /**
    * New connect creator count during this quota period
    */
    'newConnectCount'?: string;
    /**
    * Connect paired creator count during this quota period
    */
    'pairConnectCount'?: string;
    /**
    * Shop quota sum
    */
    'quotaSum'?: string;
    /**
    * Quota type, e.g. bouns quota;  period quota
    */
    'quotaType'?: string;
    /**
    * Shop quota used
    */
    'quotaUse'?: string;
    /**
    * Max creator follower count this shop can reach
    */
    'reachedMaxFollowerCnt'?: string;
    /**
    * Shop id 
    */
    'shopId'?: string;
    /**
    * Quota period start time
    */
    'startTime'?: string;
    /**
    * Is unlimited shop
    */
    'unlimited'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "string"
        },
        {
            "name": "gmvLevelRule",
            "baseName": "gmv_level_rule",
            "type": "Array<AffiliateSeller202607GetWeeklyCreatorOutreachQuotaResponseDataDataGmvLevelRule>"
        },
        {
            "name": "gmvTier",
            "baseName": "gmv_tier",
            "type": "string"
        },
        {
            "name": "newConnectCount",
            "baseName": "new_connect_count",
            "type": "string"
        },
        {
            "name": "pairConnectCount",
            "baseName": "pair_connect_count",
            "type": "string"
        },
        {
            "name": "quotaSum",
            "baseName": "quota_sum",
            "type": "string"
        },
        {
            "name": "quotaType",
            "baseName": "quota_type",
            "type": "string"
        },
        {
            "name": "quotaUse",
            "baseName": "quota_use",
            "type": "string"
        },
        {
            "name": "reachedMaxFollowerCnt",
            "baseName": "reached_max_follower_cnt",
            "type": "string"
        },
        {
            "name": "shopId",
            "baseName": "shop_id",
            "type": "string"
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "string"
        },
        {
            "name": "unlimited",
            "baseName": "unlimited",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202607GetWeeklyCreatorOutreachQuotaResponseDataData.attributeTypeMap;
    }
}

